In [43]:
import simuOpt
simuOpt.setOptions(alleleType='short', quiet=True)
import simuPOP as sim
import numpy as np
import pandas as pd
import collections
np.set_printoptions(suppress=True, precision=3)

In [17]:
np.set_printoptions(suppress=True, precision=3)

## Reading Genotype Data

In [18]:
genotypes = np.array(pd.read_csv('example_genotype_matrix.txt', sep='\t', index_col=0, low_memory=False))

In [19]:
print(genotypes)

[['2/1' '3/2' '2/3' ..., '1/2' '1/3' '3/1']
 ['2/2' '3/3' '2/2' ..., '1/2' '1/1' '3/3']
 ['2/1' '3/3' '2/2' ..., '1/2' '1/1' '3/3']
 ..., 
 ['2/2' '3/2' '2/2' ..., '2/2' '1/3' '1/1']
 ['2/2' '2/2' '2/2' ..., '1/2' '1/1' '3/3']
 ['2/2' '3/3' '2/2' ..., '1/2' '1/3' '3/3']]


In [20]:
print(genotypes[0])

['2/1' '3/2' '2/3' ..., '1/2' '1/3' '3/1']


In [21]:
genetic_map = np.array(pd.read_csv('example_genetic_map.txt', sep='\t'))

In [22]:
print(genetic_map)

[[     1.         1.        -5.511]
 [     2.         1.        -5.302]
 [     3.         1.        -5.3  ]
 ..., 
 [ 44443.        10.        89.659]
 [ 44444.        10.        89.682]
 [ 44445.        10.        89.77 ]]


In [33]:
chromosome_column = np.array(genetic_map[:, 1], dtype=np.int)

In [34]:
print(chromosome_column)

[ 1  1  1 ..., 10 10 10]


In [35]:
loci_counts = collections.Counter(chromosome_column)

In [37]:
print(loci_counts)

Counter({1: 6939, 2: 5171, 3: 4974, 5: 4838, 4: 4819, 8: 3849, 7: 3775, 6: 3570, 9: 3337, 10: 3173})


In [39]:
chromosome_lengths = [loci_counts[i] for i in range(1, 11)]

In [41]:
print(chromosome_lengths)

[6939, 5171, 4974, 4819, 4838, 3570, 3775, 3849, 3337, 3173]


In [57]:
example_pop = sim.Population(105, ploidy=2, loci=chromosome_lengths)

In [45]:
converted_genotypes = [
    [int(genotypes[ind, :][i][0]) for i in range(genotypes.shape[1])] + 
     [int(genotypes[ind, :][i][-1]) for i in range(genotypes.shape[1])] for ind in range(105)
]

In [58]:
for i, ind in enumerate(example_pop.individuals()):
    ind.setGenotype(converted_genotypes[i])

In [50]:
example_ind = example_pop.individual(0)

In [55]:
len(example_ind.genotype(ploidy=0, chroms=0))

6939

In [61]:
example_pop

<simuPOP.Population>

In [63]:
print(example_pop.popSize())

105


In [64]:
print(example_pop.numChrom())

10


In [65]:
print(example_pop.numLoci())

(6939, 5171, 4974, 4819, 4838, 3570, 3775, 3849, 3337, 3173)


In [66]:
example_individual = example_pop.individual(0)

In [71]:
example_genotype = np.array(example_individual.genotype(ploidy=0, chroms=0))

In [74]:
print(example_genotype)

[2 3 2 ..., 3 3 2]


In [75]:
example_pop.save('example_pop.pop')