In [1]:
import simuOpt

In [2]:
simuOpt.setOptions(alleleType='short', quiet=True, numThreads=4)

In [3]:
import simuPOP as sim
import numpy as np
import pandas as pd
import random
from saegus import parameters, operators
np.set_printoptions(suppress=True, precision=3)

In [4]:
from bokeh.io import output_notebook

In [5]:
from bokeh.plotting import figure, show, output_file

In [6]:
output_notebook()

Loading BokehJS ...

In [7]:
example_pop = sim.loadPopulation('example_pop.pop')

In [8]:
example_pop.infoFields()

()

In [9]:
example_pop.addInfoFields(['ind_id', 'g', 'p'])

In [10]:
example_pop.infoFields()

('ind_id', 'g', 'p')

In [11]:
print(np.array(example_pop.indInfo('ind_id')))

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


In [12]:
sim.tagID(example_pop)

In [13]:
print(np.array(example_pop.indInfo('ind_id')))

[   1.    2.    3.    4.    5.    6.    7.    8.    9.   10.   11.   12.
   13.   14.   15.   16.   17.   18.   19.   20.   21.   22.   23.   24.
   25.   26.   27.   28.   29.   30.   31.   32.   33.   34.   35.   36.
   37.   38.   39.   40.   41.   42.   43.   44.   45.   46.   47.   48.
   49.   50.   51.   52.   53.   54.   55.   56.   57.   58.   59.   60.
   61.   62.   63.   64.   65.   66.   67.   68.   69.   70.   71.   72.
   73.   74.   75.   76.   77.   78.   79.   80.   81.   82.   83.   84.
   85.   86.   87.   88.   89.   90.   91.   92.   93.   94.   95.   96.
   97.   98.   99.  100.  101.  102.  103.  104.  105.]


In [14]:
ind_ids = np.array(example_pop.indInfo('ind_id'))

In [15]:
sim.stat(example_pop, alleleFreq=sim.ALL_AVAIL)

In [16]:
sim.stat(example_pop, numOfSegSites=sim.ALL_AVAIL, 
         vars=['numOfSegSites', 'segSites', 'fixedSites'])

In [17]:
segregating_loci = example_pop.dvars().segSites

In [18]:
example_pop.dvars().numOfSegSites

42837

In [19]:
print(segregating_loci[::1000])

[0, 1040, 2072, 3098, 4124, 5156, 6199, 7217, 8248, 9282, 10338, 11361, 12392, 13407, 14468, 15502, 16562, 17599, 18637, 19665, 20700, 21766, 22805, 23813, 24837, 25882, 26910, 27923, 28955, 30026, 31057, 32103, 33142, 34173, 35185, 36207, 37223, 38243, 39351, 40419, 41477, 42537, 43578]


In [20]:
qtl = sorted(random.sample(segregating_loci, 20))

In [21]:
qtl

[1173,
 1961,
 4404,
 8233,
 14493,
 18055,
 21020,
 21096,
 21588,
 23658,
 24321,
 25107,
 29056,
 31026,
 34214,
 34973,
 37085,
 39094,
 41322,
 43463]

In [22]:
trait = parameters.Trait()

In [23]:
ae_table = trait.construct_allele_effects_table(example_pop, qtl, random.expovariate, 1)

In [24]:
ae_table[qtl]

array([[  1173.   ,      1.   ,      0.581,      2.   ,      0.507],
       [  1961.   ,      1.   ,      0.993,      2.   ,      0.614],
       [  4404.   ,      1.   ,      0.273,      3.   ,      0.311],
       [  8233.   ,      1.   ,      0.851,      3.   ,      0.58 ],
       [ 14493.   ,      1.   ,      3.453,      3.   ,      0.176],
       [ 18055.   ,      1.   ,      0.38 ,      3.   ,      0.6  ],
       [ 21020.   ,      1.   ,      0.38 ,      2.   ,      0.829],
       [ 21096.   ,      1.   ,      0.473,      3.   ,      1.047],
       [ 21588.   ,      1.   ,      5.56 ,      3.   ,      3.379],
       [ 23658.   ,      1.   ,      1.841,      3.   ,      0.439],
       [ 24321.   ,      1.   ,      0.147,      3.   ,      0.176],
       [ 25107.   ,      1.   ,      0.078,      3.   ,      1.331],
       [ 29056.   ,      1.   ,      0.67 ,      2.   ,      0.672],
       [ 31026.   ,      1.   ,      0.216,      3.   ,      1.181],
       [ 34214.   ,      1.   ,   

In [25]:
print(ae_table[qtl])

[[  1173.         1.         0.581      2.         0.507]
 [  1961.         1.         0.993      2.         0.614]
 [  4404.         1.         0.273      3.         0.311]
 [  8233.         1.         0.851      3.         0.58 ]
 [ 14493.         1.         3.453      3.         0.176]
 [ 18055.         1.         0.38       3.         0.6  ]
 [ 21020.         1.         0.38       2.         0.829]
 [ 21096.         1.         0.473      3.         1.047]
 [ 21588.         1.         5.56       3.         3.379]
 [ 23658.         1.         1.841      3.         0.439]
 [ 24321.         1.         0.147      3.         0.176]
 [ 25107.         1.         0.078      3.         1.331]
 [ 29056.         1.         0.67       2.         0.672]
 [ 31026.         1.         0.216      3.         1.181]
 [ 34214.         1.         0.982      2.         1.681]
 [ 34973.         1.         0.227      3.         1.665]
 [ 37085.         1.         0.013      2.         0.517]
 [ 39094.     

In [26]:
print(ae_table)

[[     0.      1.      0.      2.      0.]
 [     1.      2.      0.      3.      0.]
 [     2.      2.      0.      3.      0.]
 ..., 
 [ 44442.      1.      0.      2.      0.]
 [ 44443.      1.      0.      3.      0.]
 [ 44444.      1.      0.      3.      0.]]


In [27]:
ae_array = trait.construct_ae_array(ae_table, qtl)

In [28]:
print(ae_array[qtl])

[[ 0.     0.581  0.507  0.     0.   ]
 [ 0.     0.993  0.614  0.     0.   ]
 [ 0.     0.273  0.     0.311  0.   ]
 [ 0.     0.851  0.     0.58   0.   ]
 [ 0.     3.453  0.     0.176  0.   ]
 [ 0.     0.38   0.     0.6    0.   ]
 [ 0.     0.38   0.829  0.     0.   ]
 [ 0.     0.473  0.     1.047  0.   ]
 [ 0.     5.56   0.     3.379  0.   ]
 [ 0.     1.841  0.     0.439  0.   ]
 [ 0.     0.147  0.     0.176  0.   ]
 [ 0.     0.078  0.     1.331  0.   ]
 [ 0.     0.67   0.672  0.     0.   ]
 [ 0.     0.216  0.     1.181  0.   ]
 [ 0.     0.982  1.681  0.     0.   ]
 [ 0.     0.227  0.     1.665  0.   ]
 [ 0.     0.013  0.517  0.     0.   ]
 [ 0.     1.946  0.     0.194  0.   ]
 [ 0.     0.185  1.133  0.     0.   ]
 [ 0.     0.656  0.     0.479  0.   ]]


In [29]:
operators.calculate_g(example_pop, ae_array)

In [30]:
print(np.array(example_pop.indInfo('g')))

[ 45.456  40.176  37.965  41.405  41.252  39.572  46.402  39.905  40.355
  43.506  39.95   40.489  41.386  42.148  45.887  33.813  37.415  40.672
  32.261  42.834  43.176  45.556  36.994  44.856  46.136  35.563  38.953
  41.544  37.815  42.465  40.667  45.989  44.865  43.21   43.319  44.404
  44.638  47.608  39.761  41.815  42.408  40.636  36.817  43.591  46.778
  45.683  42.847  37.054  42.091  39.881  42.136  42.902  41.013  44.807
  37.048  40.595  41.883  42.687  43.029  35.544  47.205  38.281  40.684
  47.044  43.142  35.684  45.123  42.511  32.441  41.977  42.653  32.396
  41.949  46.567  45.217  46.113  44.321  42.951  35.162  45.402  44.979
  40.767  44.234  45.437  45.853  43.654  44.88   45.04   46.61   45.499
  36.715  41.73   37.677  38.64   37.969  34.728  32.108  44.946  41.238
  44.96   36.804  37.493  43.528  42.061  43.104]


In [31]:
p1 = figure(title="Distribution of g",)

In [32]:
mu, sigma = np.mean(example_pop.indInfo('g')), np.var(example_pop.indInfo('g'))

In [33]:
hist, edges = np.histogram(np.array(example_pop.indInfo('g')), density=True, bins=15)

In [34]:
edges

array([ 32.108,  33.142,  34.175,  35.208,  36.242,  37.275,  38.308,
        39.341,  40.375,  41.408,  42.441,  43.475,  44.508,  45.541,
        46.574,  47.608])

In [35]:
p1.quad(top=hist, bottom=0, left=edges[:-1], right=edges[1:], fill_color="#036564", line_color="#033649")

GlyphRenderer(id='beb9f5a2-adab-4bef-8c0c-90f74e15e698', ...)

In [36]:
from bokeh.io import export_svgs

In [ ]:
show(p1)

In [37]:
p1.output_backend = "svg"

In [38]:
export_svgs(p1, filename="g_dist.svg")

['g_dist.svg']

In [ ]:
del p1

In [ ]:
print(np.var(example_pop.indInfo('g')))

In [ ]:
print(np.mean(example_pop.indInfo('g')))

In [ ]:
heritability = 0.7

In [ ]:
np.var(example_pop.indInfo('g'))*((1/heritability) - 1)

In [ ]:
operators.calculate_error_variance(example_pop, heritability)

In [ ]:
print(example_pop.dvars().epsilon)

In [ ]:
operators.phenotypic_effect_calculator(example_pop)

In [ ]:
print(np.array(example_pop.indInfo('p')))

In [ ]:
from scipy import stats, integrate

In [ ]:
x

In [ ]:
g = np.array(example_pop.indInfo('g'))

In [ ]:
p = np.array(example_pop.indInfo('p'))

In [ ]:
operators.calculate_error_variance(example_pop, 0.7)

In [ ]:
operators.phenotypic_effect_calculator(example_pop)

In [ ]:
np.array(example_pop.indInfo('p'))

In [ ]:
np.var(example_pop.indInfo('p'))

In [ ]:
np.mean(example_pop.indInfo('p'))

In [ ]:
example_ind = example_pop.individual(0)

In [ ]:
alpha_qtl_alleles = np.array(example_ind.genotype(ploidy=0))[qtl]

In [ ]:
beta_qtl_alleles = np.array(example_ind.genotype(ploidy=1))[qtl]

In [ ]:
example_g = [[], []]
for locus, alpha, beta in zip(qtl, alpha_qtl_alleles, beta_qtl_alleles):
    print(locus, alpha, ae_array[locus, alpha], beta, ae_array[locus, beta])
    example_g[0].append(ae_array[locus, alpha])
    example_g[1].append(ae_array[locus, beta])

In [ ]:
sum(example_g[0]) + sum(example_g[1])

In [ ]:
example_pop.indByID(1).g

In [ ]:
normal_ae_table = trait.construct_allele_effects_table(example_pop, qtl, 
                                                       random.normalvariate, 0, 1)

In [ ]:
print(normal_ae_table[qtl])

In [ ]:
normal_ae_array = trait.construct_ae_array(normal_ae_table, qtl)

In [ ]:
operators.calculate_g(example_pop, normal_ae_array)

In [ ]:
print(np.array(example_pop.indInfo('g')))

In [ ]:
print(np.array(example_pop.indInfo('g')))

In [ ]:
import scipy.special

In [ ]:
from bokeh.plotting import figure, show

In [ ]:
from bokeh.io import output_notebook

In [ ]:
%%latex
    $\mathcal{N}({0, \sigma^2_g) }$

In [ ]:
p1 = figure(title="Normal Distribution (0=0, sigma=0.5)", tools="save",
           background_fill_color="#E8DDCB")

In [ ]:
output_notebook()

In [ ]:
mu, sigma = 0, 0.5

In [ ]:
measured = np.random.normal(mu, sigma, 1000)

In [ ]:
hist, edges = np.histogram(measured, density=True, bins=50)

In [ ]:
x = np.linspace(-2, 2, 1000)

In [ ]:
pdf = 1/(sigma*np.sqrt(2*np.pi)) * np.exp(-(x-mu)**2 / (2*sigma**2))

In [ ]:
cdf = (1 + scipy.special.erf((x-mu)/np.sqrt(2*sigma**2)))/2

In [ ]:
p1.quad(top=hist, bottom=0, left=edges[:-1], right=edges[1:],
    fill_color="#036564", line_color="#033649")

In [ ]:
show(p1)

In [ ]:
p1.line(x, pdf, line_color="#D95B43", line_width=8, alpha=0.7, legend="PDF")
p1.line(x, cdf, line_color="white", line_width=2, alpha=0.7, legend="CDF")

p1.legend.location = "center_right"
p1.legend.background_fill_color = "darkgrey"
p1.xaxis.axis_label = 'x'
p1.yaxis.axis_label = 'Pr(x)'

In [ ]:
output_notebook()

In [ ]:
mu = 0

In [ ]:
sigma = example_pop.dvars().epsilon

In [ ]:
error_dist = np.random.normal(0, example_pop.dvars().epsilon, 1000)

In [ ]:
hist, edges = np.histogram(error_dist, density=True, bins=50)

In [ ]:
error_dist

In [ ]:
g

In [ ]:
sigma = np.sqrt(sigma)

In [ ]:
p1.quad(top=hist, bottom=0, left=edges[:-1], right=edges[1:])

In [ ]:
edges