In [1]:
import simuOpt

In [2]:
simuOpt.setOptions(alleleType='lineage', quiet=True, numThreads=4)

In [3]:
import simuPOP as sim
import numpy as np
import pandas as pd
import random
from saegus import parameters, operators
np.set_printoptions(suppress=True, precision=3)

In [4]:
example_pop = sim.loadPopulation('example_pop.pop')

In [5]:
example_pop.infoFields()

()

In [6]:
example_pop.addInfoFields(['ind_id', 'g', 'p'])

In [7]:
example_pop.infoFields()

('ind_id', 'g', 'p')

In [8]:
sim.tagID(example_pop)

In [9]:
print(np.array(example_pop.indInfo('ind_id')))

[   1.    2.    3.    4.    5.    6.    7.    8.    9.   10.   11.   12.
   13.   14.   15.   16.   17.   18.   19.   20.   21.   22.   23.   24.
   25.   26.   27.   28.   29.   30.   31.   32.   33.   34.   35.   36.
   37.   38.   39.   40.   41.   42.   43.   44.   45.   46.   47.   48.
   49.   50.   51.   52.   53.   54.   55.   56.   57.   58.   59.   60.
   61.   62.   63.   64.   65.   66.   67.   68.   69.   70.   71.   72.
   73.   74.   75.   76.   77.   78.   79.   80.   81.   82.   83.   84.
   85.   86.   87.   88.   89.   90.   91.   92.   93.   94.   95.   96.
   97.   98.   99.  100.  101.  102.  103.  104.  105.]


In [10]:
ind_ids = np.array(example_pop.indInfo('ind_id'))

In [11]:
sim.stat(example_pop, alleleFreq=sim.ALL_AVAIL)

In [12]:
sim.stat(example_pop, numOfSegSites=sim.ALL_AVAIL, 
         vars=['numOfSegSites', 'segSites', 'fixedSites'])

In [13]:
segregating_loci = example_pop.dvars().segSites

In [14]:
example_pop.dvars().numOfSegSites

42837

In [15]:
print(segregating_loci[::1000])

[0, 1040, 2072, 3098, 4124, 5156, 6199, 7217, 8248, 9282, 10338, 11361, 12392, 13407, 14468, 15502, 16562, 17599, 18637, 19665, 20700, 21766, 22805, 23813, 24837, 25882, 26910, 27923, 28955, 30026, 31057, 32103, 33142, 34173, 35185, 36207, 37223, 38243, 39351, 40419, 41477, 42537, 43578]


In [16]:
qtl = sorted(random.sample(segregating_loci, 20))

In [46]:
qtl

[1812,
 1905,
 4802,
 6092,
 7776,
 9225,
 11426,
 17994,
 18169,
 19480,
 21206,
 22754,
 27998,
 28313,
 29297,
 31358,
 36316,
 36354,
 40565,
 44143]

In [18]:
trait = parameters.Trait()

In [19]:
ae_table = trait.construct_allele_effects_table(example_pop, qtl, random.expovariate, 1)

In [20]:
ae_table[qtl]

array([[  1812.   ,      1.   ,      2.559,      3.   ,      1.962],
       [  1905.   ,      1.   ,      0.169,      3.   ,      0.199],
       [  4802.   ,      1.   ,      0.533,      3.   ,      0.523],
       [  6092.   ,      1.   ,      0.5  ,      2.   ,      4.702],
       [  7776.   ,      1.   ,      1.825,      3.   ,      0.156],
       [  9225.   ,      1.   ,      0.793,      2.   ,      1.657],
       [ 11426.   ,      1.   ,      1.064,      3.   ,      0.228],
       [ 17994.   ,      1.   ,      0.221,      2.   ,      0.015],
       [ 18169.   ,      1.   ,      1.011,      3.   ,      1.45 ],
       [ 19480.   ,      1.   ,      1.443,      3.   ,      0.046],
       [ 21206.   ,      1.   ,      0.554,      2.   ,      1.086],
       [ 22754.   ,      1.   ,      0.904,      3.   ,      0.628],
       [ 27998.   ,      1.   ,      0.361,      2.   ,      0.023],
       [ 28313.   ,      1.   ,      1.953,      3.   ,      0.033],
       [ 29297.   ,      1.   ,   

In [21]:
ae_array = trait.construct_ae_array(ae_table, qtl)

In [22]:
ae_array[qtl]

array([[ 0.   ,  2.559,  0.   ,  1.962,  0.   ],
       [ 0.   ,  0.169,  0.   ,  0.199,  0.   ],
       [ 0.   ,  0.533,  0.   ,  0.523,  0.   ],
       [ 0.   ,  0.5  ,  4.702,  0.   ,  0.   ],
       [ 0.   ,  1.825,  0.   ,  0.156,  0.   ],
       [ 0.   ,  0.793,  1.657,  0.   ,  0.   ],
       [ 0.   ,  1.064,  0.   ,  0.228,  0.   ],
       [ 0.   ,  0.221,  0.015,  0.   ,  0.   ],
       [ 0.   ,  1.011,  0.   ,  1.45 ,  0.   ],
       [ 0.   ,  1.443,  0.   ,  0.046,  0.   ],
       [ 0.   ,  0.554,  1.086,  0.   ,  0.   ],
       [ 0.   ,  0.904,  0.   ,  0.628,  0.   ],
       [ 0.   ,  0.361,  0.023,  0.   ,  0.   ],
       [ 0.   ,  1.953,  0.   ,  0.033,  0.   ],
       [ 0.   ,  2.737,  0.   ,  3.567,  0.   ],
       [ 0.   ,  0.778,  0.   ,  1.601,  0.   ],
       [ 0.   ,  6.54 ,  0.   ,  2.131,  0.   ],
       [ 0.   ,  0.573,  1.766,  0.   ,  0.   ],
       [ 0.   ,  0.137,  0.   ,  0.351,  0.   ],
       [ 0.   ,  0.338,  0.   ,  0.719,  0.   ]])

In [23]:
operators.calculate_g(example_pop, ae_array)

In [24]:
np.array(example_pop.indInfo('g'))

array([ 40.5  ,  57.516,  42.954,  44.655,  58.748,  45.196,  44.301,
        37.803,  42.125,  48.263,  59.79 ,  46.791,  44.018,  40.228,
        46.464,  54.358,  50.271,  48.995,  49.538,  34.851,  43.836,
        47.706,  54.652,  40.614,  47.126,  48.786,  42.837,  42.593,
        54.974,  45.717,  44.98 ,  41.022,  47.093,  42.612,  47.278,
        46.156,  49.569,  45.891,  43.185,  46.977,  40.895,  39.624,
        46.451,  40.221,  41.131,  44.719,  46.342,  49.455,  42.355,
        49.107,  37.983,  46.371,  45.825,  49.369,  40.751,  42.464,
        48.045,  49.075,  47.905,  49.164,  46.342,  41.702,  41.419,
        45.088,  47.784,  48.206,  42.946,  46.279,  41.376,  48.122,
        40.604,  53.401,  43.177,  42.734,  40.98 ,  44.888,  46.668,
        43.456,  55.55 ,  43.821,  45.745,  40.688,  46.057,  44.673,
        49.514,  38.059,  40.034,  42.149,  40.867,  42.66 ,  49.946,
        44.809,  39.963,  46.583,  43.055,  49.495,  41.973,  46.353,
        43.615,  46.

In [ ]:
np.var(example_pop.indInfo('g'))

In [ ]:
np.mean(example_pop.indInfo('g'))

In [ ]:
np.median(example_pop.indInfo('g'))

In [ ]:
operators.calculate_error_variance(example_pop, 0.7)

In [ ]:
operators.phenotypic_effect_calculator(example_pop)

In [ ]:
np.array(example_pop.indInfo('p'))

In [ ]:
np.var(example_pop.indInfo('p'))

In [ ]:
np.mean(example_pop.indInfo('p'))

In [25]:
example_ind = example_pop.individual(0)

In [31]:
alpha_qtl_alleles = np.array(example_ind.genotype(ploidy=0))[qtl]

In [32]:
beta_qtl_alleles = np.array(example_ind.genotype(ploidy=1))[qtl]

In [45]:
example_g = [[], []]
for locus, alpha, beta in zip(qtl, alpha_qtl_alleles, beta_qtl_alleles):
    print(locus, alpha, ae_array[locus, alpha], beta, ae_array[locus, beta])
    example_g[0].append(ae_array[locus, alpha])
    example_g[1].append(ae_array[locus, beta])

1812 3 1.96211039471 3 1.96211039471
1905 1 0.169273516717 3 0.199434065154
4802 3 0.523146357395 1 0.532644785114
6092 1 0.499786807448 2 4.7024118054
7776 3 0.156274547953 3 0.156274547953
9225 2 1.65742251337 2 1.65742251337
11426 3 0.228257880125 3 0.228257880125
17994 2 0.0145749906999 2 0.0145749906999
18169 1 1.0108164106 1 1.0108164106
19480 3 0.0457385583349 3 0.0457385583349
21206 2 1.08615117228 1 0.554337263607
22754 3 0.628060831013 3 0.628060831013
27998 1 0.361357056286 2 0.0233817015014
28313 1 1.95254217063 1 1.95254217063
29297 1 2.73728690377 1 2.73728690377
31358 1 0.778344654131 1 0.778344654131
36316 3 2.13099766675 3 2.13099766675
36354 2 1.76630852143 2 1.76630852143
40565 1 0.136929676142 1 0.136929676142
44143 3 0.718525355568 3 0.718525355568


In [40]:
sum(example_g[0]) + sum(example_g[1])

40.500306681374511

In [44]:
example_pop.indByID(1).g

40.500306681374504