In [1]:
import simuOpt
simuOpt.setOptions(alleleType='short', quiet=True, numThreads=4)
import simuPOP as sim
import numpy as np
import pandas as pd
from saegus import breed, parse

In [2]:
np.set_printoptions(suppress=True, precision=3)

In [3]:
example_pop = sim.loadPopulation('example_pop.pop')

In [4]:
example_pop.addInfoFields(['ind_id', 'mother_id', 'father_id'])

In [5]:
sim.tagID(example_pop)

In [6]:
tf = parse.TusonFounders()

In [7]:
recom_map = tf.parse_recombination_rates('genetic_map.txt')

In [8]:
founders = [[1, 2], [3, 4], [5, 6], [7, 8]]

In [9]:
os_per_pair = 500

In [10]:
magic = breed.MAGIC(example_pop, founders, recom_map)

In [11]:
example_pop.popSize()

105

In [12]:
magic.generate_f_one(founders, os_per_pair)

In [13]:
example_pop.popSize()

2000

In [14]:
example_pop.dvars().gen

1

In [15]:
pedigrees = {}

In [16]:
pedigree = np.array((example_pop.indInfo('ind_id'), 
                     example_pop.indInfo('mother_id'), 
                     example_pop.indInfo('father_id'))).T

In [17]:
pedigree[:500]

array([[ 106.,    1.,    2.],
       [ 107.,    1.,    2.],
       [ 108.,    1.,    2.],
       ..., 
       [ 603.,    1.,    2.],
       [ 604.,    1.,    2.],
       [ 605.,    1.,    2.]])

In [18]:
pedigree[500:1000]

array([[  606.,     3.,     4.],
       [  607.,     3.,     4.],
       [  608.,     3.,     4.],
       ..., 
       [ 1103.,     3.,     4.],
       [ 1104.,     3.,     4.],
       [ 1105.,     3.,     4.]])

In [19]:
pedigree[1000:1500]

array([[ 1106.,     5.,     6.],
       [ 1107.,     5.,     6.],
       [ 1108.,     5.,     6.],
       ..., 
       [ 1603.,     5.,     6.],
       [ 1604.,     5.,     6.],
       [ 1605.,     5.,     6.]])

In [20]:
pedigree[1500:2000]

array([[ 1606.,     7.,     8.],
       [ 1607.,     7.,     8.],
       [ 1608.,     7.,     8.],
       ..., 
       [ 2103.,     7.,     8.],
       [ 2104.,     7.,     8.],
       [ 2105.,     7.,     8.]])

In [21]:
pedigrees[0] = pedigree

In [22]:
example_pop.numSubPop()

1

In [23]:
rc = breed.RandomCross(example_pop, 4, 500)

In [24]:
mothers, fathers = rc.converging_random_cross()

In [25]:
print(mothers)

[  167.   382.   424. ...,  1270.  1109.  1230.]


In [26]:
print(fathers)

[  936.   629.  1095. ...,  2020.  1722.  1773.]


In [27]:
second_order_chooser = breed.SecondOrderPairIDChooser(mothers, fathers)

In [28]:
example_pop.evolve(
        matingScheme=sim.HomoMating(
            sim.PyParentsChooser(second_order_chooser.snd_ord_id_pairs),
            sim.OffspringGenerator(ops=[
                sim.IdTagger(),
                sim.PedigreeTagger(),
                sim.Recombinator(rates=recom_map)
            ],numOffspring=1),
            subPopSize=2000,
        ),
    gen=1
)

1

In [29]:
pedigree = np.array((example_pop.indInfo('ind_id'), 
                     example_pop.indInfo('mother_id'),
                    example_pop.indInfo('father_id'))).T

In [30]:
pedigree

array([[ 2106.,   167.,   936.],
       [ 2107.,   382.,   629.],
       [ 2108.,   424.,  1095.],
       ..., 
       [ 4103.,  1270.,  2020.],
       [ 4104.,  1109.,  1722.],
       [ 4105.,  1230.,  1773.]])

In [31]:
pedigrees[1] = pedigree

In [32]:
final_random_cross = breed.RandomCross(example_pop, 2, 1000)

In [33]:
mothers, fathers = final_random_cross.converging_random_cross()

In [34]:
mothers

array([ 2217.,  2473.,  2160., ...,  2179.,  2963.,  2836.])

In [35]:
fathers

array([ 3951.,  4025.,  3355., ...,  3580.,  3464.,  4084.])

In [36]:
final_chooser = breed.SecondOrderPairIDChooser(mothers, fathers)

In [37]:
example_pop.evolve(
        matingScheme=sim.HomoMating(
            sim.PyParentsChooser(final_chooser.snd_ord_id_pairs),
            sim.OffspringGenerator(ops=[
                sim.IdTagger(),
                sim.PedigreeTagger(),
                sim.Recombinator(rates=recom_map)
            ],numOffspring=1),
            subPopSize=2000,
        ),
    gen=1
)

1

In [38]:
pedigree = np.array((example_pop.indInfo('ind_id'), 
                     example_pop.indInfo('mother_id'),
                    example_pop.indInfo('father_id'))).T

In [39]:
pedigrees[2] = pedigree

In [45]:
print(pedigrees[2])

[[ 4106.  2217.  3951.]
 [ 4107.  2473.  4025.]
 [ 4108.  2160.  3355.]
 ..., 
 [ 6103.  2179.  3580.]
 [ 6104.  2963.  3464.]
 [ 6105.  2836.  4084.]]


In [41]:
pedigrees[1]

array([[ 2106.,   167.,   936.],
       [ 2107.,   382.,   629.],
       [ 2108.,   424.,  1095.],
       ..., 
       [ 4103.,  1270.,  2020.],
       [ 4104.,  1109.,  1722.],
       [ 4105.,  1230.,  1773.]])

In [42]:
pedigrees[0]

array([[  106.,     1.,     2.],
       [  107.,     1.,     2.],
       [  108.,     1.,     2.],
       ..., 
       [ 2103.,     7.,     8.],
       [ 2104.,     7.,     8.],
       [ 2105.,     7.,     8.]])

# Multiple Replicates

In [ ]:
second_example_pop = sim.loadPopulation('example_pop.pop')

In [ ]:
second_example_pop.addInfoFields(['ind_id', 'mother_id', 'father_id'])

In [ ]:
sim.tagID(second_example_pop, reset=True)

In [ ]:
second_example_pop.indInfo('ind_id')