In [1]:
import simuOpt
simuOpt.setOptions(alleleType='short', optimized=True, quiet=True, numThreads=4)
import simuPOP as sim
import numpy as np
import pandas as pd
import h5py
from saegus import analyze

In [2]:
np.set_printoptions(precision=3, suppress=True)

In [3]:
trait = h5py.File('example_trait_data.hdf5')

In [46]:
trait['allele/states'].attrs['columns'] = list(map(np.string_, 
                                                   ['locus', 'alpha', 'omega', 'minor', 'major']))

In [47]:
trait['allele/states'].attrs['columns']

array([b'locus', b'alpha', b'omega', b'minor', b'major'], 
      dtype='|S8')

In [50]:
trait['allele/frequencies'].attrs['columns'] = list(map(np.string_, ['locus', 'alpha', 'omega', 'minor', 'major']))

In [54]:
column_names = [name.decode('UTF-8') for name in trait['allele/frequencies'].attrs['columns']]

In [55]:
column_names

['locus', 'alpha', 'omega', 'minor', 'major']

In [57]:
frq_frame = pd.DataFrame(np.array(trait['allele/frequencies']), columns=column_names)

In [59]:
example_pop = sim.loadPopulation('example_pop.pop')

In [61]:
sim.stat(example_pop, numOfSegSites=sim.ALL_AVAIL, vars=['segSites'])

In [63]:
segregating_loci = np.array(example_pop.dvars().segSites)

In [67]:
segregating_loci.dtype

dtype('int64')

In [68]:
trait['loci'] = segregating_loci

In [72]:
frq_frame

locus     alpha     omega     minor     major
0          0.0  0.319048  0.680952  0.319048  0.680952
1          1.0  0.219048  0.780952  0.219048  0.780952
2          2.0  0.938095  0.061905  0.061905  0.938095
3          3.0  0.061905  0.938095  0.061905  0.938095
4          4.0  0.690476  0.309524  0.309524  0.690476
5          5.0  0.947619  0.052381  0.052381  0.947619
6          6.0  0.204762  0.795238  0.204762  0.795238
7          7.0  0.128571  0.871429  0.128571  0.871429
8          8.0  0.133333  0.866667  0.133333  0.866667
9          9.0  0.819048  0.180952  0.180952  0.819048
10        10.0  0.538095  0.461905  0.461905  0.538095
11        11.0  0.461905  0.538095  0.461905  0.538095
12        12.0  0.090476  0.909524  0.090476  0.909524
13        13.0  0.885714  0.114286  0.114286  0.885714
14        14.0  1.000000  0.000000  0.000000  1.000000
15        15.0  1.000000  0.000000  0.000000  1.000000
16        16.0  1.000000  0.000000  0.000000  1.000000
17        17.0  0.961905  0.038095  0.038095  0.961905
18        18.0  0.128571  0.871429  0.128571  0.871429
19        19.0  0.004762  0.995238  0.004762  0.995238
20        20.0  0.295238  0.704762  0.295238  0.704762
21        21.0  0.576190  0.423810  0.423810  0.576190
22        22.0  0.214286  0.785714  0.214286  0.785714
23        23.0  0.042857  0.957143  0.042857  0.957143
24        24.0  1.000000  0.000000  0.000000  1.000000
25        25.0  0.309524  0.690476  0.309524  0.690476
26        26.0  0.223810  0.776190  0.223810  0.776190
27        27.0  1.000000  0.000000  0.000000  1.000000
28        28.0  0.104762  0.895238  0.104762  0.895238
29        29.0  1.000000  0.000000  0.000000  1.000000
...        ...       ...       ...       ...       ...
44415  44415.0  0.066667  0.933333  0.066667  0.933333
44416  44416.0  0.680952  0.319048  0.319048  0.680952
44417  44417.0  0.666667  0.333333  0.333333  0.666667
44418  44418.0  0.671429  0.328571  0.328571  0.671429
44419  44419.0  0.147619  0.852381  0.147619  0.852381
44420  44420.0  0.419048  0.580952  0.419048  0.580952
44421  44421.0  0.071429  0.928571  0.071429  0.928571
44422  44422.0  0.419048  0.580952  0.419048  0.580952
44423  44423.0  0.166667  0.833333  0.166667  0.833333
44424  44424.0  0.919048  0.080952  0.080952  0.919048
44425  44425.0  0.704762  0.295238  0.295238  0.704762
44426  44426.0  0.819048  0.180952  0.180952  0.819048
44427  44427.0  0.028571  0.971429  0.028571  0.971429
44428  44428.0  0.828571  0.171429  0.171429  0.828571
44429  44429.0  0.080952  0.919048  0.080952  0.919048
44430  44430.0  0.542857  0.457143  0.457143  0.542857
44431  44431.0  0.385714  0.614286  0.385714  0.614286
44432  44432.0  0.176190  0.823810  0.176190  0.823810
44433  44433.0  0.376190  0.623810  0.376190  0.623810
44434  44434.0  0.457143  0.542857  0.457143  0.542857
44435  44435.0  0.561905  0.438095  0.438095  0.561905
44436  44436.0  0.380952  0.619048  0.380952  0.619048
44437  44437.0  0.385714  0.614286  0.385714  0.614286
44438  44438.0  0.457143  0.542857  0.457143  0.542857
44439  44439.0  0.542857  0.457143  0.457143  0.542857
44440  44440.0  0.457143  0.542857  0.457143  0.542857
44441  44441.0  0.542857  0.457143  0.457143  0.542857
44442  44442.0  0.533333  0.466667  0.466667  0.533333
44443  44443.0  0.738095  0.261905  0.261905  0.738095
44444  44444.0  0.266667  0.733333  0.266667  0.733333

[44445 rows x 5 columns]

In [242]:
minor_major_allele_effects[:, 1] = minor_alleles

In [21]:
allele_effects = pd.DataFrame(np.array(trait['allele/effects']))

In [86]:
qtl = np.array(trait['qtl'])

In [87]:
qtl

array([  425,  4144,  6564,  6912,  8943,  9326, 11437, 11480, 13064,
       16309, 18787, 22171, 23093, 28903, 34913, 35493, 38448, 43071,
       43499, 44043])

In [35]:
list(trait['allele/frequencies'].shape)

[44445, 5]

In [81]:
q_values = pd.read_csv('example_q_values.txt', sep='\t')

In [82]:
q_values

q
0      0.926890
1      0.925767
2      0.924884
3      0.920301
4      0.895577
5      0.895577
6      0.921135
7      0.895577
8      0.895577
9      0.895577
10     0.895577
11     0.895577
12     0.895577
13     0.921135
17     0.895577
18     0.895577
19     0.905517
20     0.895577
21     0.910853
22     0.895577
23     0.895577
25     0.933371
26     0.925559
28     0.925640
30     0.895577
31     0.895577
32     0.895577
33     0.921135
34     0.929973
35     0.921135
...         ...
44415  0.917455
44416  0.895577
44417  0.899665
44418  0.915643
44419  0.921135
44420  0.914597
44421  0.921135
44422  0.895577
44423  0.895577
44424  0.921135
44425  0.895577
44426  0.898042
44427  0.895577
44428  0.924884
44429  0.925640
44430  0.906780
44431  0.921135
44432  0.925640
44433  0.924884
44434  0.906780
44435  0.895577
44436  0.925767
44437  0.921135
44438  0.906780
44439  0.906780
44440  0.906780
44441  0.906780
44442  0.909373
44443  0.895577
44444  0.921135

[42837 rows x 1 columns]

In [17]:
pwd

'/home/vakanas/BISB/rjwlab-scripts/saegus_project/src/docs/user_guide'

In [7]:
allele_effects[qtl]

array([[   425.   ,      1.   ,      0.5  ,      3.   ,      1.478],
       [  4144.   ,      1.   ,      1.247,      2.   ,      1.602],
       [  6564.   ,      1.   ,      0.753,      3.   ,      0.578],
       [  6912.   ,      1.   ,      0.339,      3.   ,      0.011],
       [  8943.   ,      1.   ,      0.521,      3.   ,      0.085],
       [  9326.   ,      1.   ,      1.031,      3.   ,      2.298],
       [ 11437.   ,      1.   ,      2.155,      3.   ,      2.336],
       [ 11480.   ,      1.   ,      1.291,      3.   ,      2.774],
       [ 13064.   ,      1.   ,      0.287,      2.   ,      0.527],
       [ 16309.   ,      1.   ,      0.911,      3.   ,      0.5  ],
       [ 18787.   ,      1.   ,      1.05 ,      3.   ,      3.014],
       [ 22171.   ,      1.   ,      0.213,      3.   ,      0.786],
       [ 23093.   ,      1.   ,      1.551,      3.   ,      2.961],
       [ 28903.   ,      1.   ,      3.625,      3.   ,      1.119],
       [ 34913.   ,      1.   ,   

In [115]:
np.array(trait['allele/states'])[425, 3]

3.0

In [117]:
mafrqs = np.array(mafrqs)

In [122]:
sum(mafrqs[:, 3] <= 0.5)

44445

In [ ]:
mafrqs[:, 3]

In [124]:
allele_states = np.array(trait['allele/states'])

In [127]:
minor_alleles = allele_states[:, 3]

In [208]:
allele_states

array([[     0.,      1.,      2.,      1.,      2.],
       [     1.,      2.,      3.,      2.,      3.],
       [     2.,      2.,      3.,      3.,      2.],
       ..., 
       [ 44442.,      1.,      2.,      2.,      1.],
       [ 44443.,      1.,      3.,      3.,      1.],
       [ 44444.,      1.,      3.,      1.,      3.]])

In [128]:
mafrqs

array([[     0.   ,      0.319,      0.681,      0.319,      0.681],
       [     1.   ,      0.219,      0.781,      0.219,      0.781],
       [     2.   ,      0.938,      0.062,      0.062,      0.938],
       ..., 
       [ 44442.   ,      0.533,      0.467,      0.467,      0.533],
       [ 44443.   ,      0.738,      0.262,      0.262,      0.738],
       [ 44444.   ,      0.267,      0.733,      0.267,      0.733]])

In [130]:
sim.stat(example_pop, alleleFreq=sim.ALL_AVAIL)

In [131]:
example_pop.dvars().alleleFreq

{0: defdict({1: 0.319047619047619, 2: 0.680952380952381}),
 1: defdict({2: 0.21904761904761905, 3: 0.780952380952381}),
 2: defdict({2: 0.9380952380952381, 3: 0.06190476190476191}),
 3: defdict({1: 0.06190476190476191, 3: 0.9380952380952381}),
 4: defdict({1: 0.6904761904761905, 3: 0.30952380952380953}),
 5: defdict({1: 0.9476190476190476, 3: 0.05238095238095238}),
 6: defdict({1: 0.20476190476190476, 3: 0.7952380952380952}),
 7: defdict({1: 0.12857142857142856, 3: 0.8714285714285714}),
 8: defdict({1: 0.13333333333333333, 3: 0.8666666666666667}),
 9: defdict({2: 0.819047619047619, 3: 0.18095238095238095}),
 10: defdict({1: 0.5380952380952381, 3: 0.46190476190476193}),
 11: defdict({1: 0.46190476190476193, 2: 0.5380952380952381}),
 12: defdict({1: 0.09047619047619047, 3: 0.9095238095238095}),
 13: defdict({1: 0.8857142857142857, 3: 0.11428571428571428}),
 14: defdict({1: 1.0}),
 15: defdict({3: 1.0}),
 16: defdict({1: 1.0}),
 17: defdict({1: 0.9619047619047619, 2: 0.0380952380952381}),

In [133]:
allele_effects = np.array(allele_effects)

In [144]:
minor_alpha = np.where(allele_effects[:, 1] == minor_alleles)[0]

In [148]:
minor_alpha.shape

(24122,)

In [145]:
minor_omega = np.where(allele_effects[:, 3] == minor_alleles)[0]

In [147]:
minor_omega.shape

(20323,)

In [150]:
minor_alpha.shape[0] + minor_omega.shape[0]

44445

In [152]:
allele_effects[minor_alpha]

array([[     0.,      1.,      0.,      2.,      0.],
       [     1.,      2.,      0.,      3.,      0.],
       [     3.,      1.,      0.,      3.,      0.],
       ..., 
       [ 44438.,      1.,      0.,      3.,      0.],
       [ 44440.,      1.,      0.,      3.,      0.],
       [ 44444.,      1.,      0.,      3.,      0.]])

In [154]:
allele_effects[minor_alpha, 1]

array([ 1.,  2.,  1., ...,  1.,  1.,  1.])

In [155]:
allele_effects[minor_omega, 1]

array([ 2.,  1.,  1., ...,  1.,  1.,  1.])

In [ ]:
allele

In [74]:
raw_gwas_results = pd.read_csv('example_2.txt', sep='\t')

In [76]:
raw_gwas_results.drop(0, axis=0, inplace=True)

In [77]:
raw_gwas_results.drop('Trait', axis=1, inplace=True)

In [79]:
raw_gwas_results.index = np.array(list(map(int, raw_gwas_results.Marker)))

In [80]:
raw_gwas_results.index

Int64Index([    0,     1,     2,     3,     4,     5,     6,     7,     8,
                9,
            ...
            44435, 44436, 44437, 44438, 44439, 44440, 44441, 44442, 44443,
            44444],
           dtype='int64', length=42837)

In [92]:
segregating_frequencies = frq_frame.ix[segregating_loci, :]

In [93]:
segregating_frequencies

locus     alpha     omega     minor     major
0          0.0  0.319048  0.680952  0.319048  0.680952
1          1.0  0.219048  0.780952  0.219048  0.780952
2          2.0  0.938095  0.061905  0.061905  0.938095
3          3.0  0.061905  0.938095  0.061905  0.938095
4          4.0  0.690476  0.309524  0.309524  0.690476
5          5.0  0.947619  0.052381  0.052381  0.947619
6          6.0  0.204762  0.795238  0.204762  0.795238
7          7.0  0.128571  0.871429  0.128571  0.871429
8          8.0  0.133333  0.866667  0.133333  0.866667
9          9.0  0.819048  0.180952  0.180952  0.819048
10        10.0  0.538095  0.461905  0.461905  0.538095
11        11.0  0.461905  0.538095  0.461905  0.538095
12        12.0  0.090476  0.909524  0.090476  0.909524
13        13.0  0.885714  0.114286  0.114286  0.885714
17        17.0  0.961905  0.038095  0.038095  0.961905
18        18.0  0.128571  0.871429  0.128571  0.871429
19        19.0  0.004762  0.995238  0.004762  0.995238
20        20.0  0.295238  0.704762  0.295238  0.704762
21        21.0  0.576190  0.423810  0.423810  0.576190
22        22.0  0.214286  0.785714  0.214286  0.785714
23        23.0  0.042857  0.957143  0.042857  0.957143
25        25.0  0.309524  0.690476  0.309524  0.690476
26        26.0  0.223810  0.776190  0.223810  0.776190
28        28.0  0.104762  0.895238  0.104762  0.895238
30        30.0  0.100000  0.900000  0.100000  0.900000
31        31.0  0.128571  0.871429  0.128571  0.871429
32        32.0  0.319048  0.680952  0.319048  0.680952
33        33.0  0.195238  0.804762  0.195238  0.804762
34        34.0  0.280952  0.719048  0.280952  0.719048
35        35.0  0.071429  0.928571  0.071429  0.928571
...        ...       ...       ...       ...       ...
44415  44415.0  0.066667  0.933333  0.066667  0.933333
44416  44416.0  0.680952  0.319048  0.319048  0.680952
44417  44417.0  0.666667  0.333333  0.333333  0.666667
44418  44418.0  0.671429  0.328571  0.328571  0.671429
44419  44419.0  0.147619  0.852381  0.147619  0.852381
44420  44420.0  0.419048  0.580952  0.419048  0.580952
44421  44421.0  0.071429  0.928571  0.071429  0.928571
44422  44422.0  0.419048  0.580952  0.419048  0.580952
44423  44423.0  0.166667  0.833333  0.166667  0.833333
44424  44424.0  0.919048  0.080952  0.080952  0.919048
44425  44425.0  0.704762  0.295238  0.295238  0.704762
44426  44426.0  0.819048  0.180952  0.180952  0.819048
44427  44427.0  0.028571  0.971429  0.028571  0.971429
44428  44428.0  0.828571  0.171429  0.171429  0.828571
44429  44429.0  0.080952  0.919048  0.080952  0.919048
44430  44430.0  0.542857  0.457143  0.457143  0.542857
44431  44431.0  0.385714  0.614286  0.385714  0.614286
44432  44432.0  0.176190  0.823810  0.176190  0.823810
44433  44433.0  0.376190  0.623810  0.376190  0.623810
44434  44434.0  0.457143  0.542857  0.457143  0.542857
44435  44435.0  0.561905  0.438095  0.438095  0.561905
44436  44436.0  0.380952  0.619048  0.380952  0.619048
44437  44437.0  0.385714  0.614286  0.385714  0.614286
44438  44438.0  0.457143  0.542857  0.457143  0.542857
44439  44439.0  0.542857  0.457143  0.457143  0.542857
44440  44440.0  0.457143  0.542857  0.457143  0.542857
44441  44441.0  0.542857  0.457143  0.457143  0.542857
44442  44442.0  0.533333  0.466667  0.466667  0.533333
44443  44443.0  0.738095  0.261905  0.261905  0.738095
44444  44444.0  0.266667  0.733333  0.266667  0.733333

[42837 rows x 5 columns]

In [104]:
segregating_ae_effects = np.array(trait['allele/effects'])[segregating_loci, :]

In [107]:
segregating_ae_effects_frame = pd.DataFrame(segregating_ae_effects, columns=['aelocus', 
                                                                             'a_state', 
                                                                             'a_effect', 
                                                                             'o_state', 'o_effect'])

In [99]:
frq_joined_table = joined_gwas_results.join(segregating_frequencies)

In [83]:
joined_gwas_results = raw_gwas_results.join(q_values)

In [85]:
qtl

array(['effects', 'frequencies', 'states'], 
      dtype='<U11')

In [88]:
joined_gwas_results.ix[425, :]

Marker                  425
Chr                       1
Pos                     403
df                        1
F                   0.07797
p                   0.78064
add_effect              NaN
add_F                   NaN
add_p                   NaN
dom_effect              NaN
dom_F                   NaN
dom_p                   NaN
errordf                 105
MarkerR2          0.0007475
Genetic Var         0.00115
Residual Var        24.2831
-2LnLikelihood      663.779
q                  0.923195
Name: 425, dtype: object

In [108]:
complete_table = frq_joined_table.join(segregating_ae_effects_frame)

In [109]:
complete_table

Marker   Chr      Pos  df        F        p  add_effect     add_F  \
0          0   1.0      0.0   2  0.07400  0.92873    0.313980  0.089030   
1          1   1.0      1.0   2  0.10165  0.90344   -0.181180  0.022890   
2          2   1.0      2.0   2  0.22440  0.79940   -1.921300  0.370510   
3          3   1.0      3.0   2  0.47379  0.62403    1.902390  0.363700   
4          4   1.0      4.0   1  2.30936  0.13172         NaN       NaN   
5          5   1.0      5.0   2  1.19680  0.30645    4.163440  1.628700   
6          6   1.0      6.0   2  0.36444  0.69551   -1.242100  0.629180   
7          7   1.0      7.0   2  1.10292  0.33590    1.800160  0.864870   
8          8   1.0      8.0   2  0.93496  0.39601    1.867350  0.931550   
9          9   1.0      9.0   2  1.99032  0.14203   -3.250200  3.526200   
10        10   1.0     10.0   1  3.12305  0.08021         NaN       NaN   
11        11   1.0     11.0   1  3.12305  0.08021         NaN       NaN   
12        12   1.0     12.0   2  1.99130  0.14189    6.537600  3.834940   
13        13   1.0     13.0   2  0.42545  0.65466   -1.609100  0.722760   
17        17   1.0     14.0   1  1.61257  0.20705         NaN       NaN   
18        18   1.0     15.0   2  2.97037  0.05583    6.656630  3.973370   
19        19   1.0     16.0   1  0.46800  0.49547         NaN       NaN   
20        20   1.0     17.0   2  2.37335  0.09840    2.246810  4.196640   
21        21   1.0     18.0   2  0.62940  0.53501   -1.046000  1.112540   
22        22   1.0     19.0   2  0.93956  0.39422    1.754770  1.696600   
23        23   1.0     20.0   1  1.45979  0.22978         NaN       NaN   
25        25   1.0     21.0   2  0.00534  0.99467   -0.032172  0.000914   
26        26   1.0     22.0   1  0.03254  0.85722         NaN       NaN   
28        28   1.0     23.0   2  0.11857  0.88831   -1.086900  0.178690   
30        30   1.0     24.0   2  0.92814  0.39867   -4.438100  1.856130   
31        31   1.0     25.0   2  3.29175  0.04126    5.785060  6.453260   
32        32   1.0     26.0   2  0.86651  0.42355    0.825750  0.494130   
33        33   1.0     27.0   2  0.37906  0.68548   -0.676270  0.466940   
34        34   1.0     28.0   2  0.03876  0.96199    0.080590  0.006160   
35        35   1.0     29.0   2  0.30052  0.74110    0.111880  0.003530   
...      ...   ...      ...  ..      ...      ...         ...       ...   
44415  44415  10.0  42807.0   2  0.53716  0.58608    0.263680  0.006850   
44416  44416  10.0  42808.0   2  2.67222  0.07403    0.095800  0.010590   
44417  44417  10.0  42809.0   2  0.77848  0.46187   -0.545670  0.370760   
44418  44418  10.0  42810.0   2  0.57023  0.56722   -0.466880  0.273640   
44419  44419  10.0  42811.0   2  0.44235  0.64378    1.359890  0.849960   
44420  44420  10.0  42812.0   2  0.57854  0.56258    0.272830  0.083640   
44421  44421  10.0  42813.0   2  0.42334  0.65602   -0.441200  0.019110   
44422  44422  10.0  42814.0   2  1.12985  0.32717    1.080840  1.298960   
44423  44423  10.0  42815.0   2  1.06176  0.34971   -1.790800  1.208980   
44424  44424  10.0  42816.0   1  0.15164  0.69779         NaN       NaN   
44425  44425  10.0  42817.0   2  2.57892  0.08089   -0.274890  0.050930   
44426  44426  10.0  42818.0   2  0.83684  0.43609   -0.471990  0.083100   
44427  44427  10.0  42819.0   2  2.06708  0.13193   -2.853800  1.543150   
44428  44428  10.0  42820.0   2  0.20183  0.81756    0.806060  0.362530   
44429  44429  10.0  42821.0   2  0.11570  0.89086    0.800390  0.137720   
44430  44430  10.0  42822.0   2  0.69970  0.49915    0.339150  0.128040   
44431  44431  10.0  42823.0   1  0.09974  0.75280         NaN       NaN   
44432  44432  10.0  42824.0   2  0.14126  0.86844    0.646020  0.104470   
44433  44433  10.0  42825.0   2  0.20110  0.81816   -0.501600  0.235770   
44434  44434  10.0  42826.0   2  0.69970  0.49915   -0.339150  0.128040   
44435  44435  10.0  42827.0   2  1.15979  0.31773    0.489380  0.248850   
44436  44436  10.0  42828.0   2

In [3]:
gwas_results = pd.read_csv('/home/vakanas/tassel-5-standalone/example_2.txt', sep='\t', index_col=0)

In [7]:
example_pop = sim.loadPopulation('example_pop.pop')

In [9]:
sim.stat(example_pop, numOfSegSites=sim.ALL_AVAIL, vars=['numOfSegSites', 'segSites'])

In [11]:
seg_loci = np.array(example_pop.dvars().segSites)

In [26]:
seg_loci.dtype

dtype('int64')

In [24]:
markers = np.array(np.array(gwas_results.Marker)[1:], dtype=np.int_)

In [33]:
markers

array([    0,     1,     2, ..., 44442, 44443, 44444])

In [37]:
sum(gwas_results.add_p < 0.05)

1463

In [38]:
qvals = pd.read_csv("/home/vakanas/tassel-5-standalone/example_q_values.txt", sep="\t", index_col=0)

In [43]:
qvals

q
1      0.993609
2      0.993609
3      0.997369
4      0.993609
5      0.993609
6      0.993609
7      0.996347
8      0.993609
9      0.993609
10     0.993609
11     0.997512
12     0.997512
13     0.995169
14     0.997512
15     0.993609
16     0.993609
17     0.993609
18     0.993609
19     0.993609
20     0.997512
21     0.993609
22     0.993609
23     0.993609
24     0.997512
25     0.993609
26     0.993609
27     0.993609
28     0.993609
29     0.993609
30     0.995337
...         ...
42808  0.993609
42809  0.993609
42810  0.993609
42811  0.993609
42812  0.993609
42813  0.995865
42814  0.993609
42815  0.993609
42816  0.993609
42817  0.993609
42818  0.993609
42819  0.993609
42820  0.993609
42821  0.993609
42822  0.993609
42823  0.993609
42824  0.993609
42825  0.993609
42826  0.993609
42827  0.993609
42828  0.993609
42829  0.993609
42830  0.993609
42831  0.993609
42832  0.993609
42833  0.993609
42834  0.993609
42835  0.993609
42836  0.993609
42837  0.993609

[42837 rows x 1 columns]

In [156]:
from saegus import parameters

In [157]:
trait = parameters.Trait()

In [158]:
allele_effects

array([[     0.,      1.,      0.,      2.,      0.],
       [     1.,      2.,      0.,      3.,      0.],
       [     2.,      2.,      0.,      3.,      0.],
       ..., 
       [ 44442.,      1.,      0.,      2.,      0.],
       [ 44443.,      1.,      0.,      3.,      0.],
       [ 44444.,      1.,      0.,      3.,      0.]])

In [159]:
allele_effects_array = trait.construct_ae_array(allele_effects, qtl)

In [161]:
allele_effects_array[qtl]

array([[ 0.   ,  0.5  ,  0.   ,  1.478,  0.   ],
       [ 0.   ,  1.247,  1.602,  0.   ,  0.   ],
       [ 0.   ,  0.753,  0.   ,  0.578,  0.   ],
       [ 0.   ,  0.339,  0.   ,  0.011,  0.   ],
       [ 0.   ,  0.521,  0.   ,  0.085,  0.   ],
       [ 0.   ,  1.031,  0.   ,  2.298,  0.   ],
       [ 0.   ,  2.155,  0.   ,  2.336,  0.   ],
       [ 0.   ,  1.291,  0.   ,  2.774,  0.   ],
       [ 0.   ,  0.287,  0.527,  0.   ,  0.   ],
       [ 0.   ,  0.911,  0.   ,  0.5  ,  0.   ],
       [ 0.   ,  1.05 ,  0.   ,  3.014,  0.   ],
       [ 0.   ,  0.213,  0.   ,  0.786,  0.   ],
       [ 0.   ,  1.551,  0.   ,  2.961,  0.   ],
       [ 0.   ,  3.625,  0.   ,  1.119,  0.   ],
       [ 0.   ,  2.637,  0.   ,  0.026,  0.   ],
       [ 0.   ,  0.846,  0.047,  0.   ,  0.   ],
       [ 0.   ,  0.376,  0.   ,  2.122,  0.   ],
       [ 0.   ,  0.446,  0.   ,  2.095,  0.   ],
       [ 0.   ,  0.114,  0.   ,  0.027,  0.   ],
       [ 0.   ,  0.19 ,  0.   ,  0.107,  0.   ]])

In [163]:
allele_effects_array[minor_alpha, :]

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [164]:
minor_major_allele_effects = np.zeros((44445, 5))

In [165]:
minor_alleles

array([ 1.,  2.,  3., ...,  2.,  3.,  1.])

In [166]:
minor_major_allele_effects[..., 0] = minor_alleles

In [167]:
minor_major_allele_effects

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 2.,  0.,  0.,  0.,  0.],
       [ 3.,  0.,  0.,  0.,  0.],
       ..., 
       [ 2.,  0.,  0.,  0.,  0.],
       [ 3.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.]])

In [168]:
allele_effects_array[minor_alpha, minor_alleles[minor_alpha]]

IndexError: arrays used as indices must be of integer (or boolean) type

In [171]:
minor_alpha

array([    0,     1,     3, ..., 44438, 44440, 44444])

In [170]:
minor_alleles[minor_alpha]

array([ 1.,  2.,  1., ...,  1.,  1.,  1.])

In [175]:
allele_effects_array[0, 1]

0.0

In [178]:
425 in minor_alpha

False

In [177]:
425 in minor_omega

True

In [179]:
minor_omega

array([    2,     4,     5, ..., 44441, 44442, 44443])

In [181]:
allele_states[425, 3]

3.0

In [182]:
allele_effects_array[425, 3]

1.4782369407614042

In [186]:
minor_alleles[minor_alpha]

array([ 1.,  2.,  1., ...,  1.,  1.,  1.])

In [195]:
minor_alleles

dtype('float64')

In [196]:
allele_effects.dtype

dtype('float64')

In [197]:
allele_effects[0, np.int(minor_alleles[0])]

1.0

In [198]:
for locus in minor_alpha:
    print(locus)
    print(allele_effects_array[locus, np.int(minor_alleles[locus])])
    
    break

0
0.0


In [202]:
for qtlocus in qtl:
    if qtlocus in minor_alpha:
        print("Locus {} Minor Allele {}".format(qtlocus, np.int(minor_alleles[qtlocus])))
        print(allele_effects_array[qtlocus, np.int(minor_alleles[qtlocus])])
    if qtlocus in minor_omega:
        print("Locus {} Minor Allele {}".format(qtlocus, np.int(minor_alleles[qtlocus])))
        print(allele_effects_array[qtlocus, np.int(minor_alleles[qtlocus])])

Locus 425 Minor Allele 3
1.47823694076
Locus 4144 Minor Allele 2
1.60174869067
Locus 6564 Minor Allele 3
0.577546867727
Locus 6912 Minor Allele 3
0.0111025586224
Locus 8943 Minor Allele 3
0.0851526128178
Locus 9326 Minor Allele 1
1.03113107187
Locus 11437 Minor Allele 3
2.33613174
Locus 11480 Minor Allele 3
2.77400967079
Locus 13064 Minor Allele 1
0.287260644742
Locus 16309 Minor Allele 1
0.910758110651
Locus 18787 Minor Allele 1
1.04983746183
Locus 22171 Minor Allele 3
0.786236665896
Locus 23093 Minor Allele 3
2.96102285221
Locus 28903 Minor Allele 1
3.62515437819
Locus 34913 Minor Allele 1
2.63676335271
Locus 35493 Minor Allele 2
0.0471615330795
Locus 38448 Minor Allele 1
0.375972775891
Locus 43071 Minor Allele 1
0.446402823225
Locus 43499 Minor Allele 3
0.0269224163755
Locus 44043 Minor Allele 3
0.107164985614


In [204]:
for qtlocus in qtl:
    if qtlocus in minor_alpha:
        minor_major_allele_effects[qtlocus, 1] = allele_effects_array[qtlocus, np.int(minor_alleles[qtlocus])]
        print("Locus {} Minor Allele {}".format(qtlocus, np.int(minor_alleles[qtlocus])))
        print(allele_effects_array[qtlocus, np.int(minor_alleles[qtlocus])])
    if qtlocus in minor_omega:
        minor_major_allele_effects[qtlocus, 1] = allele_effects_array[qtlocus, np.int(minor_alleles[qtlocus])]
        print("Locus {} Minor Allele {}".format(qtlocus, np.int(minor_alleles[qtlocus])))
        print(allele_effects_array[qtlocus, np.int(minor_alleles[qtlocus])])

Locus 425 Minor Allele 3
1.47823694076
Locus 4144 Minor Allele 2
1.60174869067
Locus 6564 Minor Allele 3
0.577546867727
Locus 6912 Minor Allele 3
0.0111025586224
Locus 8943 Minor Allele 3
0.0851526128178
Locus 9326 Minor Allele 1
1.03113107187
Locus 11437 Minor Allele 3
2.33613174
Locus 11480 Minor Allele 3
2.77400967079
Locus 13064 Minor Allele 1
0.287260644742
Locus 16309 Minor Allele 1
0.910758110651
Locus 18787 Minor Allele 1
1.04983746183
Locus 22171 Minor Allele 3
0.786236665896
Locus 23093 Minor Allele 3
2.96102285221
Locus 28903 Minor Allele 1
3.62515437819
Locus 34913 Minor Allele 1
2.63676335271
Locus 35493 Minor Allele 2
0.0471615330795
Locus 38448 Minor Allele 1
0.375972775891
Locus 43071 Minor Allele 1
0.446402823225
Locus 43499 Minor Allele 3
0.0269224163755
Locus 44043 Minor Allele 3
0.107164985614


In [206]:
minor_major_allele_effects[qtl]

array([[ 3.   ,  1.478,  0.   ,  0.   ,  0.   ],
       [ 2.   ,  1.602,  0.   ,  0.   ,  0.   ],
       [ 3.   ,  0.578,  0.   ,  0.   ,  0.   ],
       [ 3.   ,  0.011,  0.   ,  0.   ,  0.   ],
       [ 3.   ,  0.085,  0.   ,  0.   ,  0.   ],
       [ 1.   ,  1.031,  0.   ,  0.   ,  0.   ],
       [ 3.   ,  2.336,  0.   ,  0.   ,  0.   ],
       [ 3.   ,  2.774,  0.   ,  0.   ,  0.   ],
       [ 1.   ,  0.287,  0.   ,  0.   ,  0.   ],
       [ 1.   ,  0.911,  0.   ,  0.   ,  0.   ],
       [ 1.   ,  1.05 ,  0.   ,  0.   ,  0.   ],
       [ 3.   ,  0.786,  0.   ,  0.   ,  0.   ],
       [ 3.   ,  2.961,  0.   ,  0.   ,  0.   ],
       [ 1.   ,  3.625,  0.   ,  0.   ,  0.   ],
       [ 1.   ,  2.637,  0.   ,  0.   ,  0.   ],
       [ 2.   ,  0.047,  0.   ,  0.   ,  0.   ],
       [ 1.   ,  0.376,  0.   ,  0.   ,  0.   ],
       [ 1.   ,  0.446,  0.   ,  0.   ,  0.   ],
       [ 3.   ,  0.027,  0.   ,  0.   ,  0.   ],
       [ 3.   ,  0.107,  0.   ,  0.   ,  0.   ]])

In [173]:
minor_alleles

array([ 1.,  2.,  3., ...,  2.,  3.,  1.])

In [207]:
allele_states

array([[     0.,      1.,      2.,      1.,      2.],
       [     1.,      2.,      3.,      2.,      3.],
       [     2.,      2.,      3.,      3.,      2.],
       ..., 
       [ 44442.,      1.,      2.,      2.,      1.],
       [ 44443.,      1.,      3.,      3.,      1.],
       [ 44444.,      1.,      3.,      1.,      3.]])

In [209]:
major_alleles = allele_states[:, 4]

In [213]:
allele_effects

array([[     0.,      1.,      0.,      2.,      0.],
       [     1.,      2.,      0.,      3.,      0.],
       [     2.,      2.,      0.,      3.,      0.],
       ..., 
       [ 44442.,      1.,      0.,      2.,      0.],
       [ 44443.,      1.,      0.,      3.,      0.],
       [ 44444.,      1.,      0.,      3.,      0.]])

In [214]:
major_alpha = np.where(allele_states[:, 4] == major_alleles)[0]

In [216]:
major_alpha.shape

(44445,)

In [217]:
allele_states

array([[     0.,      1.,      2.,      1.,      2.],
       [     1.,      2.,      3.,      2.,      3.],
       [     2.,      2.,      3.,      3.,      2.],
       ..., 
       [ 44442.,      1.,      2.,      2.,      1.],
       [ 44443.,      1.,      3.,      3.,      1.],
       [ 44444.,      1.,      3.,      1.,      3.]])

In [227]:
major_alpha = np.where(allele_effects[:, 1] == major_alleles)[0]

In [241]:
allele_effects

array([[     0.,      1.,      0.,      2.,      0.],
       [     1.,      2.,      0.,      3.,      0.],
       [     2.,      2.,      0.,      3.,      0.],
       ..., 
       [ 44442.,      1.,      0.,      2.,      0.],
       [ 44443.,      1.,      0.,      3.,      0.],
       [ 44444.,      1.,      0.,      3.,      0.]])

In [228]:
major_alpha.shape

(20323,)

In [229]:
major_omega = np.where(allele_effects[:, 3] == major_alleles)[0]

In [230]:
major_omega.shape

(24122,)

In [232]:
for qtlocus in qtl:
    if qtlocus in major_alpha:
        print("Locus {} Major Allele {}".format(qtlocus, np.int(major_alleles[qtlocus])))
        print(allele_effects_array[qtlocus, np.int(major_alleles[qtlocus])])
    if qtlocus in major_omega:
        print("Locus {} Major Allele {}".format(qtlocus, np.int(major_alleles[qtlocus])))
        print(allele_effects_array[qtlocus, np.int(major_alleles[qtlocus])])

Locus 425 Major Allele 1
0.500309485784
Locus 4144 Major Allele 1
1.24657118888
Locus 6564 Major Allele 1
0.753262610119
Locus 6912 Major Allele 1
0.339146831844
Locus 8943 Major Allele 1
0.521383614985
Locus 9326 Major Allele 3
2.2981668026
Locus 11437 Major Allele 1
2.15457257681
Locus 11480 Major Allele 1
1.29103258284
Locus 13064 Major Allele 2
0.527112118455
Locus 16309 Major Allele 3
0.499950206874
Locus 18787 Major Allele 3
3.01428834712
Locus 22171 Major Allele 1
0.213086956737
Locus 23093 Major Allele 1
1.55077378167
Locus 28903 Major Allele 3
1.11943358073
Locus 34913 Major Allele 3
0.0264481016375
Locus 35493 Major Allele 1
0.846023028423
Locus 38448 Major Allele 3
2.12220415511
Locus 43071 Major Allele 3
2.09517537875
Locus 43499 Major Allele 1
0.113878677782
Locus 44043 Major Allele 1
0.189574770616


In [234]:
minor_major_allele_effects[qtl]

array([[ 3.   ,  1.478,  0.   ,  0.   ,  0.   ],
       [ 2.   ,  1.602,  0.   ,  0.   ,  0.   ],
       [ 3.   ,  0.578,  0.   ,  0.   ,  0.   ],
       [ 3.   ,  0.011,  0.   ,  0.   ,  0.   ],
       [ 3.   ,  0.085,  0.   ,  0.   ,  0.   ],
       [ 1.   ,  1.031,  0.   ,  0.   ,  0.   ],
       [ 3.   ,  2.336,  0.   ,  0.   ,  0.   ],
       [ 3.   ,  2.774,  0.   ,  0.   ,  0.   ],
       [ 1.   ,  0.287,  0.   ,  0.   ,  0.   ],
       [ 1.   ,  0.911,  0.   ,  0.   ,  0.   ],
       [ 1.   ,  1.05 ,  0.   ,  0.   ,  0.   ],
       [ 3.   ,  0.786,  0.   ,  0.   ,  0.   ],
       [ 3.   ,  2.961,  0.   ,  0.   ,  0.   ],
       [ 1.   ,  3.625,  0.   ,  0.   ,  0.   ],
       [ 1.   ,  2.637,  0.   ,  0.   ,  0.   ],
       [ 2.   ,  0.047,  0.   ,  0.   ,  0.   ],
       [ 1.   ,  0.376,  0.   ,  0.   ,  0.   ],
       [ 1.   ,  0.446,  0.   ,  0.   ,  0.   ],
       [ 3.   ,  0.027,  0.   ,  0.   ,  0.   ],
       [ 3.   ,  0.107,  0.   ,  0.   ,  0.   ]])

In [235]:
minor_major_allele_effects[..., 2] = major_alleles

In [237]:
minor_major_allele_effects[qtl]

array([[ 3.   ,  1.478,  1.   ,  0.   ,  0.   ],
       [ 2.   ,  1.602,  1.   ,  0.   ,  0.   ],
       [ 3.   ,  0.578,  1.   ,  0.   ,  0.   ],
       [ 3.   ,  0.011,  1.   ,  0.   ,  0.   ],
       [ 3.   ,  0.085,  1.   ,  0.   ,  0.   ],
       [ 1.   ,  1.031,  3.   ,  0.   ,  0.   ],
       [ 3.   ,  2.336,  1.   ,  0.   ,  0.   ],
       [ 3.   ,  2.774,  1.   ,  0.   ,  0.   ],
       [ 1.   ,  0.287,  2.   ,  0.   ,  0.   ],
       [ 1.   ,  0.911,  3.   ,  0.   ,  0.   ],
       [ 1.   ,  1.05 ,  3.   ,  0.   ,  0.   ],
       [ 3.   ,  0.786,  1.   ,  0.   ,  0.   ],
       [ 3.   ,  2.961,  1.   ,  0.   ,  0.   ],
       [ 1.   ,  3.625,  3.   ,  0.   ,  0.   ],
       [ 1.   ,  2.637,  3.   ,  0.   ,  0.   ],
       [ 2.   ,  0.047,  1.   ,  0.   ,  0.   ],
       [ 1.   ,  0.376,  3.   ,  0.   ,  0.   ],
       [ 1.   ,  0.446,  3.   ,  0.   ,  0.   ],
       [ 3.   ,  0.027,  1.   ,  0.   ,  0.   ],
       [ 3.   ,  0.107,  1.   ,  0.   ,  0.   ]])

In [238]:
for qtlocus in qtl:
    if qtlocus in major_alpha:
        minor_major_allele_effects[qtlocus, 3] = allele_effects_array[qtlocus, np.int(major_alleles[qtlocus])]
        print("Locus {} Major Allele {}".format(qtlocus, np.int(major_alleles[qtlocus])))
        print(allele_effects_array[qtlocus, np.int(major_alleles[qtlocus])])
    if qtlocus in major_omega:
        minor_major_allele_effects[qtlocus, 3] = allele_effects_array[qtlocus, np.int(major_alleles[qtlocus])]
        print("Locus {} Major Allele {}".format(qtlocus, np.int(major_alleles[qtlocus])))
        print(allele_effects_array[qtlocus, np.int(major_alleles[qtlocus])])

Locus 425 Major Allele 1
0.500309485784
Locus 4144 Major Allele 1
1.24657118888
Locus 6564 Major Allele 1
0.753262610119
Locus 6912 Major Allele 1
0.339146831844
Locus 8943 Major Allele 1
0.521383614985
Locus 9326 Major Allele 3
2.2981668026
Locus 11437 Major Allele 1
2.15457257681
Locus 11480 Major Allele 1
1.29103258284
Locus 13064 Major Allele 2
0.527112118455
Locus 16309 Major Allele 3
0.499950206874
Locus 18787 Major Allele 3
3.01428834712
Locus 22171 Major Allele 1
0.213086956737
Locus 23093 Major Allele 1
1.55077378167
Locus 28903 Major Allele 3
1.11943358073
Locus 34913 Major Allele 3
0.0264481016375
Locus 35493 Major Allele 1
0.846023028423
Locus 38448 Major Allele 3
2.12220415511
Locus 43071 Major Allele 3
2.09517537875
Locus 43499 Major Allele 1
0.113878677782
Locus 44043 Major Allele 1
0.189574770616


In [240]:
minor_major_allele_effects[qtl]

array([[ 3.   ,  1.478,  1.   ,  0.5  ,  0.   ],
       [ 2.   ,  1.602,  1.   ,  1.247,  0.   ],
       [ 3.   ,  0.578,  1.   ,  0.753,  0.   ],
       [ 3.   ,  0.011,  1.   ,  0.339,  0.   ],
       [ 3.   ,  0.085,  1.   ,  0.521,  0.   ],
       [ 1.   ,  1.031,  3.   ,  2.298,  0.   ],
       [ 3.   ,  2.336,  1.   ,  2.155,  0.   ],
       [ 3.   ,  2.774,  1.   ,  1.291,  0.   ],
       [ 1.   ,  0.287,  2.   ,  0.527,  0.   ],
       [ 1.   ,  0.911,  3.   ,  0.5  ,  0.   ],
       [ 1.   ,  1.05 ,  3.   ,  3.014,  0.   ],
       [ 3.   ,  0.786,  1.   ,  0.213,  0.   ],
       [ 3.   ,  2.961,  1.   ,  1.551,  0.   ],
       [ 1.   ,  3.625,  3.   ,  1.119,  0.   ],
       [ 1.   ,  2.637,  3.   ,  0.026,  0.   ],
       [ 2.   ,  0.047,  1.   ,  0.846,  0.   ],
       [ 1.   ,  0.376,  3.   ,  2.122,  0.   ],
       [ 1.   ,  0.446,  3.   ,  2.095,  0.   ],
       [ 3.   ,  0.027,  1.   ,  0.114,  0.   ],
       [ 3.   ,  0.107,  1.   ,  0.19 ,  0.   ]])