In [1]:
import simuOpt
simuOpt.setOptions(alleleType='short', quiet=True, numThreads=4)
import simuPOP as sim
import numpy as np, pandas as pd
from scipy import stats
from saegus import parameters, breed, parse

In [2]:
np.set_printoptions(suppress=True, precision=3)

In [3]:
example_pop = sim.loadPopulation('example_pop.pop')

In [4]:
example_pop.addInfoFields(['ind_id', 'father_id', 'mother_id', 'primary'])

In [5]:
sim.tagID(example_pop)

In [6]:
example_pop.indInfo('ind_id')

(1.0,
 2.0,
 3.0,
 4.0,
 5.0,
 6.0,
 7.0,
 8.0,
 9.0,
 10.0,
 11.0,
 12.0,
 13.0,
 14.0,
 15.0,
 16.0,
 17.0,
 18.0,
 19.0,
 20.0,
 21.0,
 22.0,
 23.0,
 24.0,
 25.0,
 26.0,
 27.0,
 28.0,
 29.0,
 30.0,
 31.0,
 32.0,
 33.0,
 34.0,
 35.0,
 36.0,
 37.0,
 38.0,
 39.0,
 40.0,
 41.0,
 42.0,
 43.0,
 44.0,
 45.0,
 46.0,
 47.0,
 48.0,
 49.0,
 50.0,
 51.0,
 52.0,
 53.0,
 54.0,
 55.0,
 56.0,
 57.0,
 58.0,
 59.0,
 60.0,
 61.0,
 62.0,
 63.0,
 64.0,
 65.0,
 66.0,
 67.0,
 68.0,
 69.0,
 70.0,
 71.0,
 72.0,
 73.0,
 74.0,
 75.0,
 76.0,
 77.0,
 78.0,
 79.0,
 80.0,
 81.0,
 82.0,
 83.0,
 84.0,
 85.0,
 86.0,
 87.0,
 88.0,
 89.0,
 90.0,
 91.0,
 92.0,
 93.0,
 94.0,
 95.0,
 96.0,
 97.0,
 98.0,
 99.0,
 100.0,
 101.0,
 102.0,
 103.0,
 104.0,
 105.0)

In [7]:
structure_matrix = pd.read_csv('example_population_structure_matrix.txt', index_col=0)

In [8]:
popst = parameters.PopulationStructure(example_pop)

In [9]:
proportions = np.array(np.array(structure_matrix)[:, 1:7])

In [10]:
proportions

array([[0.0, 0.9996, 0.0, 0.0004, 0.0, 0.0],
       [0.011000000000000001, 0.0015, 0.0004, 0.1047, 0.0, 0.8824],
       [0.0, 0.3832, 0.0, 0.6168, 0.0, 0.0],
       [0.0, 0.4085, 0.5134, 0.0782, 0.0, 0.0],
       [0.0, 0.0009, 0.0, 0.0048, 0.0, 0.9943],
       [0.2195, 0.0198, 0.021, 0.2371, 0.1295, 0.3731],
       [0.0, 0.4907, 0.0, 0.5093, 0.0, 0.0],
       [0.9994, 0.0, 0.0, 0.0006, 0.0, 0.0],
       [0.4155, 0.0079, 0.0007, 0.5736, 0.0005, 0.0018],
       [0.0, 0.4622, 0.0, 0.5378, 0.0, 0.0],
       [0.0, 0.0003, 0.0, 0.0115, 0.0, 0.9882],
       [0.0, 0.0, 0.0, 1.0, 0.0, 0.0],
       [0.9243, 0.001, 0.0008, 0.0729, 0.001, 0.0],
       [0.3813, 0.0014, 0.6129, 0.0024, 0.0008, 0.0012],
       [0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
       [0.0908, 0.0184, 0.0014, 0.1178, 0.0044, 0.7673],
       [0.0009, 0.0014, 0.0, 0.2705, 0.7262, 0.001],
       [0.0055, 0.5564, 0.0047, 0.0324, 0.3745, 0.0265],
       [0.0009, 0.0026, 0.0024, 0.2734, 0.7198, 0.0009],
       [0.0, 0.9961, 0.0, 0.0039, 0.0, 

In [11]:
np.sum(proportions, axis=1)

array([1.0, 1.0, 1.0, 1.0001, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
       1.0, 1.0, 1.0001, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.9999, 1.0, 1.0,
       1.0, 1.0, 1.0, 1.0, 0.9999999999999999, 1.0, 1.0, 1.0,
       1.0000000000000002, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0001, 1.0, 1.0,
       1.0, 1.0, 1.0, 1.0, 1.0, 0.9999000000000001, 1.0001, 1.0, 1.0, 1.0,
       1.0, 1.0, 0.9999999999999999, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
       1.0, 1.0, 0.9999, 0.9999999999999999, 1.0, 1.0, 1.0, 1.0, 1.0,
       0.9999999999999999, 1.0, 1.0, 1.0, 1.0, 1.0, 0.9999, 1.0,
       0.9999999999999999, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
       1.0, 1.0, 0.9999999999999999, 1.0, 1.0, 1.0, 1.0, 1.0, 0.9999,
       0.9999, 1.0, 1.0, 0.9999999999999999, 1.0, 1.0], dtype=object)

In [12]:
proportions[33]

array([0.8857, 0.0016, 0.0009, 0.1065, 0.0042, 0.0011], dtype=object)

In [13]:
sum(proportions[33])

1.0000000000000002

In [14]:
sum(proportions[5])

1.0

In [15]:
corrected_proportions = popst.correct_rounding_error(proportions)

In [16]:
corrected_proportions[33]

array([0.8856999999999998, 0.0016, 0.0009, 0.1065, 0.0042, 0.0011], dtype=object)

In [17]:
sum(corrected_proportions[33])

0.9999999999999999

In [ ]:
corrected_proportions[104]

In [ ]:
example_pop.popSize()

In [18]:
mating_pmfs = {}
for i, ind in enumerate(example_pop.individuals()):
    mating_pmfs[ind.ind_id] = stats.rv_discrete(values=([0.0, 1.0, 2.0, 3.0, 4.0, 5.0], 
                                                        corrected_proportions[i]), name=str(ind.ind_id))

In [25]:
corrected_proportions[5]

array([0.2195, 0.0198, 0.021, 0.2371, 0.1295, 0.3731], dtype=object)

In [26]:
import collections as col

In [33]:
mating_pmfs[6].pk

array([0.2195, 0.0198, 0.021, 0.2371, 0.1295, 0.3731], dtype=object)

In [34]:
draw_results = mating_pmfs[6].rvs(size=1000)

In [35]:
draw_results

array([4, 3, 5, 3, 3, 0, 3, 5, 5, 5, 5, 4, 5, 4, 4, 0, 5, 4, 3, 5, 3, 0, 0,
       0, 5, 4, 0, 4, 5, 3, 5, 2, 4, 5, 5, 0, 5, 3, 3, 4, 0, 5, 5, 5, 5, 0,
       3, 3, 3, 3, 4, 2, 5, 1, 5, 5, 5, 4, 5, 3, 3, 3, 0, 3, 5, 5, 3, 5, 3,
       3, 0, 3, 3, 3, 0, 4, 5, 5, 3, 3, 3, 0, 5, 5, 5, 2, 3, 5, 3, 5, 5, 0,
       0, 0, 5, 5, 0, 5, 3, 5, 5, 0, 5, 4, 5, 1, 0, 4, 0, 3, 0, 4, 0, 3, 5,
       0, 0, 5, 3, 3, 3, 3, 0, 5, 0, 3, 2, 4, 5, 1, 3, 5, 3, 5, 0, 5, 3, 5,
       0, 5, 0, 0, 5, 5, 5, 1, 5, 0, 4, 3, 5, 5, 3, 5, 3, 5, 3, 0, 5, 5, 1,
       5, 3, 5, 3, 5, 3, 4, 5, 3, 3, 3, 4, 3, 5, 3, 5, 2, 4, 0, 3, 5, 4, 5,
       2, 3, 5, 3, 4, 0, 4, 3, 4, 5, 5, 5, 4, 4, 5, 5, 5, 0, 4, 0, 5, 2, 5,
       5, 3, 5, 5, 5, 0, 0, 3, 5, 3, 5, 5, 5, 5, 3, 5, 5, 3, 5, 5, 3, 5, 0,
       3, 1, 3, 0, 3, 5, 0, 0, 4, 3, 0, 5, 5, 3, 5, 3, 4, 0, 5, 4, 0, 3, 3,
       5, 0, 3, 0, 5, 0, 3, 5, 0, 5, 5, 0, 5, 5, 3, 3, 5, 3, 3, 0, 4, 5, 0,
       4, 4, 0, 3, 5, 5, 4, 0, 3, 5, 5, 0, 5, 4, 3, 0, 3, 3, 5, 5, 0, 0, 3,
       0, 4,

In [36]:
draw_counts = col.Counter(draw_results)

In [39]:
draw_counts

Counter({0: 219, 1: 17, 2: 21, 3: 223, 4: 148, 5: 372})

In [40]:
draw_frequencies = []
for sp in range(6):
    draw_frequencies.append(draw_counts[sp]/1000)

In [41]:
draw_frequencies

[0.219, 0.017, 0.021, 0.223, 0.148, 0.372]

In [44]:
corrected_proportions[5]

array([0.2195, 0.0198, 0.021, 0.2371, 0.1295, 0.3731], dtype=object)

In [56]:
example_pop.dvars().mating_probabilities = mating_pmfs

In [57]:
popst_parent_chooser = breed.ForcedPopulationStructureParentChooser(1000, mating_pmfs)

In [46]:
primary_subpops = {ind.ind_id: float(np.argmax(corrected_proportions[i])) 
                   for i, ind in enumerate(example_pop.individuals())}

In [47]:
primary_subpops

{1.0: 1.0,
 2.0: 5.0,
 3.0: 3.0,
 4.0: 2.0,
 5.0: 5.0,
 6.0: 5.0,
 7.0: 3.0,
 8.0: 0.0,
 9.0: 3.0,
 10.0: 3.0,
 11.0: 5.0,
 12.0: 3.0,
 13.0: 0.0,
 14.0: 2.0,
 15.0: 1.0,
 16.0: 5.0,
 17.0: 4.0,
 18.0: 1.0,
 19.0: 4.0,
 20.0: 1.0,
 21.0: 3.0,
 22.0: 1.0,
 23.0: 5.0,
 24.0: 3.0,
 25.0: 1.0,
 26.0: 5.0,
 27.0: 4.0,
 28.0: 3.0,
 29.0: 5.0,
 30.0: 1.0,
 31.0: 2.0,
 32.0: 1.0,
 33.0: 1.0,
 34.0: 0.0,
 35.0: 3.0,
 36.0: 3.0,
 37.0: 3.0,
 38.0: 1.0,
 39.0: 0.0,
 40.0: 0.0,
 41.0: 5.0,
 42.0: 0.0,
 43.0: 2.0,
 44.0: 3.0,
 45.0: 3.0,
 46.0: 1.0,
 47.0: 1.0,
 48.0: 4.0,
 49.0: 1.0,
 50.0: 0.0,
 51.0: 0.0,
 52.0: 3.0,
 53.0: 2.0,
 54.0: 3.0,
 55.0: 2.0,
 56.0: 2.0,
 57.0: 0.0,
 58.0: 3.0,
 59.0: 3.0,
 60.0: 2.0,
 61.0: 3.0,
 62.0: 2.0,
 63.0: 1.0,
 64.0: 3.0,
 65.0: 1.0,
 66.0: 5.0,
 67.0: 1.0,
 68.0: 3.0,
 69.0: 2.0,
 70.0: 5.0,
 71.0: 0.0,
 72.0: 5.0,
 73.0: 0.0,
 74.0: 3.0,
 75.0: 3.0,
 76.0: 1.0,
 77.0: 3.0,
 78.0: 3.0,
 79.0: 5.0,
 80.0: 1.0,
 81.0: 5.0,
 82.0: 2.0,
 83.0: 3.0,
 84.0: 1.0,
 

In [48]:
for ind in example_pop.individuals():
    ind.primary = primary_subpops[ind.ind_id]

In [49]:
example_pop.indInfo('primary')

(1.0,
 5.0,
 3.0,
 2.0,
 5.0,
 5.0,
 3.0,
 0.0,
 3.0,
 3.0,
 5.0,
 3.0,
 0.0,
 2.0,
 1.0,
 5.0,
 4.0,
 1.0,
 4.0,
 1.0,
 3.0,
 1.0,
 5.0,
 3.0,
 1.0,
 5.0,
 4.0,
 3.0,
 5.0,
 1.0,
 2.0,
 1.0,
 1.0,
 0.0,
 3.0,
 3.0,
 3.0,
 1.0,
 0.0,
 0.0,
 5.0,
 0.0,
 2.0,
 3.0,
 3.0,
 1.0,
 1.0,
 4.0,
 1.0,
 0.0,
 0.0,
 3.0,
 2.0,
 3.0,
 2.0,
 2.0,
 0.0,
 3.0,
 3.0,
 2.0,
 3.0,
 2.0,
 1.0,
 3.0,
 1.0,
 5.0,
 1.0,
 3.0,
 2.0,
 5.0,
 0.0,
 5.0,
 0.0,
 3.0,
 3.0,
 1.0,
 3.0,
 3.0,
 5.0,
 1.0,
 5.0,
 2.0,
 3.0,
 1.0,
 1.0,
 0.0,
 3.0,
 3.0,
 3.0,
 0.0,
 4.0,
 3.0,
 0.0,
 4.0,
 2.0,
 2.0,
 2.0,
 3.0,
 3.0,
 0.0,
 0.0,
 3.0,
 3.0,
 4.0,
 3.0)

In [50]:
primary_subpopulation_splitter = sim.InfoSplitter(field='primary', 
                                                  values=[0.0, 1.0, 2.0, 3.0, 4.0, 5.0])

In [51]:
example_pop.setVirtualSplitter(primary_subpopulation_splitter)

In [53]:
tf = parse.TusonFounders()

In [54]:
recom_rates = tf.parse_recombination_rates('genetic_map.txt')

In [55]:
recom_rates

[0.0020926625899999962,
 2.2615580000007186e-05,
 0.00042822784999999361,
 0.00031254837999999729,
 0.0014689310100000075,
 0.00020776456000000111,
 0.0012046017399999975,
 0.0004001773199999992,
 0.0023329853400000022,
 0.00084844494999999573,
 0.00020627060000000697,
 0.0034117589199999989,
 0.00055784244999999898,
 1.7850339999991859e-05,
 0.0021015491200000016,
 0.0015734830000000023,
 0.0040656016799999993,
 0.00026672478000000055,
 3.0703610000002435e-05,
 0.0001470012899999995,
 3.271269999998161e-06,
 4.3016000000006823e-06,
 5.2572210000003671e-05,
 4.1393219999998899e-05,
 0.005212608379999999,
 0.00023272412999999936,
 0.0047767046199999989,
 0.0042987637000000013,
 2.5242900000002065e-05,
 2.2332239999995896e-05,
 0.0025030401100000032,
 0.00052706154999999867,
 0.001750234850000001,
 0.00018942481999999927,
 0.00069979514999999996,
 0.0046152015499999997,
 3.9796209999999333e-05,
 0.001775915640000001,
 2.8127809999999308e-05,
 8.8994119999999949e-05,
 2.3671659999999762e-

In [58]:
example_pop.evolve(
    matingScheme=sim.HomoMating(
        sim.PyParentsChooser(popst_parent_chooser.forced_structure_parent_chooser),
        sim.OffspringGenerator(
            ops=[sim.IdTagger(), sim.PedigreeTagger(), sim.Recombinator(recom_rates)],
                numOffspring=1),
        subPopSize=1000
    ),
    gen=1
)

1

In [59]:
pedigree = np.array((example_pop.indInfo('ind_id'), 
                     example_pop.indInfo('mother_id'), 
                     example_pop.indInfo('father_id'))).T

In [60]:
pedigree

array([[  106.,    45.,    86.],
       [  107.,    26.,    70.],
       [  108.,    60.,    31.],
       ..., 
       [ 1103.,    63.,    65.],
       [ 1104.,    20.,    67.],
       [ 1105.,    39.,    40.]])