In [1]:
import simuOpt
simuOpt.setOptions(alleleType='lineage', quiet=True)
import simuPOP as sim
import numpy as np, pandas as pd
from scipy import stats
from saegus import parameters, breed

In [3]:
np.set_printoptions(suppress=True, precision=3)

In [4]:
example_pop = sim.loadPopulation('example_pop.pop')

In [5]:
example_pop.addInfoFields(['ind_id', 'father_id', 'mother_id', 'primary'])

In [6]:
sim.tagID(example_pop)

In [10]:
structure_matrix = pd.read_csv('example_population_structure_matrix.txt', index_col=0)

In [11]:
structure_matrix

sample_id       1       2       3       4       5       6         sample  \
0            1  0.0000  0.9996  0.0000  0.0004  0.0000  0.0000  C0_062314_002   
1            2  0.0110  0.0015  0.0004  0.1047  0.0000  0.8824  C0_062314_003   
2            3  0.0000  0.3832  0.0000  0.6168  0.0000  0.0000  C0_062314_004   
3            4  0.0000  0.4085  0.5134  0.0782  0.0000  0.0000  C0_062314_005   
4            5  0.0000  0.0009  0.0000  0.0048  0.0000  0.9943  C0_062314_006   
5            6  0.2195  0.0198  0.0210  0.2371  0.1295  0.3731  C0_062314_007   
6            7  0.0000  0.4907  0.0000  0.5093  0.0000  0.0000  C0_062314_009   
7            8  0.9994  0.0000  0.0000  0.0006  0.0000  0.0000  C0_062314_010   
8            9  0.4155  0.0079  0.0007  0.5736  0.0005  0.0018  C0_062314_011   
9           10  0.0000  0.4622  0.0000  0.5378  0.0000  0.0000  C0_062314_012   
10          11  0.0000  0.0003  0.0000  0.0115  0.0000  0.9882  C0_062314_013   
11          12  0.0000  0.0000  0.0000  1.0000  0.0000  0.0000  C0_062314_014   
12          13  0.9243  0.0010  0.0008  0.0729  0.0010  0.0000  C0_062314_015   
13          14  0.3813  0.0014  0.6129  0.0024  0.0008  0.0012  C0_062314_016   
14          15  0.0000  1.0000  0.0000  0.0000  0.0000  0.0000  C0_062314_018   
15          16  0.0908  0.0184  0.0014  0.1178  0.0044  0.7673  C0_062314_019   
16          17  0.0009  0.0014  0.0000  0.2705  0.7262  0.0010  C0_062314_020   
17          18  0.0055  0.5564  0.0047  0.0324  0.3745  0.0265  C0_062314_021   
18          19  0.0009  0.0026  0.0024  0.2734  0.7198  0.0009  C0_062314_022   
19          20  0.0000  0.9961  0.0000  0.0039  0.0000  0.0000  C0_062314_023   
20          21  0.0000  0.3802  0.0000  0.6198  0.0000  0.0000  C0_062314_024   
21          22  0.0000  1.0000  0.0000  0.0000  0.0000  0.0000  C0_062314_025   
22          23  0.0620  0.0012  0.0093  0.1665  0.0342  0.7267  C0_062314_026   
23          24  0.0000  0.0000  0.0000  1.0000  0.0000  0.0000  C0_062314_027   
24          25  0.0000  1.0000  0.0000  0.0000  0.0000  0.0000  C0_062314_028   
25          26  0.1668  0.0030  0.0022  0.1614  0.0722  0.5944  C0_062314_029   
26          27  0.0071  0.0020  0.0012  0.2184  0.7706  0.0007  C0_062314_030   
27          28  0.0000  0.3532  0.0000  0.6468  0.0000  0.0000  C0_062314_031   
28          29  0.0000  0.0000  0.0000  0.0000  0.0000  1.0000  C0_062314_033   
29          30  0.0005  0.9509  0.0000  0.0486  0.0000  0.0000  C0_062314_034   
..         ...     ...     ...     ...     ...     ...     ...            ...   
75          76  0.0000  0.9990  0.0000  0.0010  0.0000  0.0000  C0_062314_084   
76          77  0.3899  0.0116  0.0010  0.5908  0.0058  0.0009  C0_062314_086   
77          78  0.0000  0.0000  0.0000  1.0000  0.0000  0.0000  C0_062314_087   
78          79  0.0877  0.0071  0.0010  0.0766  0.0004  0.8271  C0_062314_088   
79          80  0.0000  0.9988  0.0000  0.0012  0.0000  0.0000  C0_062314_090   
80          81  0.2025  0.0389  0.0143  0.1339  0.0614  0.5490  C0_062314_091   
81          82  0.4697  0.0002  0.5291  0.0010  0.0000  0.0000  C0_062314_092   
82          83  0.0000  0.4866  0.0000  0.5134  0.0000  0.0000  C0_062314_093   
83          84  0.0000  0.5080  0.0000  0.4920  0.0000  0.0000  C0_062314_094   
84          85  0.0000  0.9983  0.0000  0.0017  0.0000  0.0000  C0_062314_095   
85          86  0.9360  0.0016  0.0010  0.0605  0.0000  0.0009  C0_062314_096   
86          87  0.0000  0.0000  0.0000  1.0000  0.0000  0.0000  C0_062314_097   
87          88  0.0000  0.3879  0.0000  0.6121  0.0000  0.0000       C0_164_1   
88          89  0.0000  0.4803  0.0000  0.5197  0.0000  0.0000       C0_164_2   
89          90  0.9215  0.0016  0.0010  0.0743  0.0003  0.0013       C0_164_3   
90          91  0.0034  0.0010  0.0016  0.2526  0.7407  0.0007       C0_164_4   
91          92  0.0000  0.4778  0.0000  0.5222  0.0000  0.0000       C0_164_5   
92          93  0.9932  0.0020  0.00

In [7]:
np.array(structure_matrix.ix[structure_matrix['sample_id'] == 3])

NameError: name 'structure_matrix' is not defined

In [20]:
corrected_structure_matrix = popst.correct_structure_matrix(structure_matrix)

AttributeError: 'PopulationStructure' object has no attribute 'correct_structure_matrix'

In [14]:
np.array(structure_matrix)[0]

array([1, 0.0, 0.9996, 0.0, 0.0004, 0.0, 0.0, 'C0_062314_002', 27,
       'C0_062314_030'], dtype=object)

In [41]:
remapped_array = np.empty((105, 10), dtype=np.object)

In [43]:
for i in range(1, 106):
    remapped_array[i-1] = np.array(structure_matrix.ix[structure_matrix['sample_id'] == i])

In [47]:
remapped_data_frame = pd.DataFrame(remapped_array, columns=structure_matrix.columns)

In [59]:
remapped_data_frame.to_csv('remapped_population_structure_matrix.txt', index=None)

In [60]:
testing_remapped_popst = pd.read_csv('remapped_population_structure_matrix.txt')

In [173]:
testing_remapped_popst

sample_id       1       2       3       4       5       6         sample  \
0            1  0.0000  0.9996  0.0000  0.0004  0.0000  0.0000  C0_062314_002   
1            2  0.0110  0.0015  0.0004  0.1047  0.0000  0.8824  C0_062314_003   
2            3  0.0000  0.3832  0.0000  0.6168  0.0000  0.0000  C0_062314_004   
3            4  0.0000  0.4085  0.5134  0.0782  0.0000  0.0000  C0_062314_005   
4            5  0.0000  0.0009  0.0000  0.0048  0.0000  0.9943  C0_062314_006   
5            6  0.2195  0.0198  0.0210  0.2371  0.1295  0.3731  C0_062314_007   
6            7  0.0000  0.4907  0.0000  0.5093  0.0000  0.0000  C0_062314_009   
7            8  0.9994  0.0000  0.0000  0.0006  0.0000  0.0000  C0_062314_010   
8            9  0.4155  0.0079  0.0007  0.5736  0.0005  0.0018  C0_062314_011   
9           10  0.0000  0.4622  0.0000  0.5378  0.0000  0.0000  C0_062314_012   
10          11  0.0000  0.0003  0.0000  0.0115  0.0000  0.9882  C0_062314_013   
11          12  0.0000  0.0000  0.0000  1.0000  0.0000  0.0000  C0_062314_014   
12          13  0.9243  0.0010  0.0008  0.0729  0.0010  0.0000  C0_062314_015   
13          14  0.3813  0.0014  0.6129  0.0024  0.0008  0.0012  C0_062314_016   
14          15  0.0000  1.0000  0.0000  0.0000  0.0000  0.0000  C0_062314_018   
15          16  0.0908  0.0184  0.0014  0.1178  0.0044  0.7673  C0_062314_019   
16          17  0.0009  0.0014  0.0000  0.2705  0.7262  0.0010  C0_062314_020   
17          18  0.0055  0.5564  0.0047  0.0324  0.3745  0.0265  C0_062314_021   
18          19  0.0009  0.0026  0.0024  0.2734  0.7198  0.0009  C0_062314_022   
19          20  0.0000  0.9961  0.0000  0.0039  0.0000  0.0000  C0_062314_023   
20          21  0.0000  0.3802  0.0000  0.6198  0.0000  0.0000  C0_062314_024   
21          22  0.0000  1.0000  0.0000  0.0000  0.0000  0.0000  C0_062314_025   
22          23  0.0620  0.0012  0.0093  0.1665  0.0342  0.7267  C0_062314_026   
23          24  0.0000  0.0000  0.0000  1.0000  0.0000  0.0000  C0_062314_027   
24          25  0.0000  1.0000  0.0000  0.0000  0.0000  0.0000  C0_062314_028   
25          26  0.1668  0.0030  0.0022  0.1614  0.0722  0.5944  C0_062314_029   
26          27  0.0071  0.0020  0.0012  0.2184  0.7706  0.0007  C0_062314_030   
27          28  0.0000  0.3532  0.0000  0.6468  0.0000  0.0000  C0_062314_031   
28          29  0.0000  0.0000  0.0000  0.0000  0.0000  1.0000  C0_062314_033   
29          30  0.0005  0.9509  0.0000  0.0486  0.0000  0.0000  C0_062314_034   
..         ...     ...     ...     ...     ...     ...     ...            ...   
75          76  0.0000  0.9990  0.0000  0.0010  0.0000  0.0000  C0_062314_084   
76          77  0.3899  0.0116  0.0010  0.5908  0.0058  0.0009  C0_062314_086   
77          78  0.0000  0.0000  0.0000  1.0000  0.0000  0.0000  C0_062314_087   
78          79  0.0877  0.0071  0.0010  0.0766  0.0004  0.8271  C0_062314_088   
79          80  0.0000  0.9988  0.0000  0.0012  0.0000  0.0000  C0_062314_090   
80          81  0.2025  0.0389  0.0143  0.1339  0.0614  0.5490  C0_062314_091   
81          82  0.4697  0.0002  0.5291  0.0010  0.0000  0.0000  C0_062314_092   
82          83  0.0000  0.4866  0.0000  0.5134  0.0000  0.0000  C0_062314_093   
83          84  0.0000  0.5080  0.0000  0.4920  0.0000  0.0000  C0_062314_094   
84          85  0.0000  0.9983  0.0000  0.0017  0.0000  0.0000  C0_062314_095   
85          86  0.9360  0.0016  0.0010  0.0605  0.0000  0.0009  C0_062314_096   
86          87  0.0000  0.0000  0.0000  1.0000  0.0000  0.0000  C0_062314_097   
87          88  0.0000  0.3879  0.0000  0.6121  0.0000  0.0000       C0_164_1   
88          89  0.0000  0.4803  0.0000  0.5197  0.0000  0.0000       C0_164_2   
89          90  0.9215  0.0016  0.0010  0.0743  0.0003  0.0013       C0_164_3   
90          91  0.0034  0.0010  0.0016  0.2526  0.7407  0.0007       C0_164_4   
91          92  0.0000  0.4778  0.0000  0.5222  0.0000  0.0000       C0_164_5   
92          93  0.9932  0.0020  0.00

In [15]:
popst = parameters.PopulationStructure(example_pop)

In [16]:
proportions = np.array(np.array(structure_matrix)[:, 1:7])

In [136]:
struct_func = stats.rv_discrete(values=pmf_value, name=str())

In [139]:
struct_func.rvs(size=100)

array([4, 1, 2, 4, 4, 1, 1, 1, 6, 6, 1, 4, 1, 6, 6, 1, 4, 1, 6, 4, 6, 6, 4,
       6, 6, 1, 5, 3, 1, 5, 6, 6, 4, 6, 5, 4, 5, 1, 1, 1, 1, 4, 1, 1, 6, 4,
       4, 4, 3, 4, 4, 6, 4, 6, 4, 4, 5, 5, 6, 6, 4, 1, 3, 5, 1, 4, 5, 1, 4,
       4, 1, 5, 6, 6, 4, 4, 6, 4, 1, 1, 6, 1, 1, 5, 4, 4, 4, 6, 6, 5, 1, 6,
       4, 1, 5, 5, 6, 2, 1, 5])

In [9]:
remapped_matrix = popst.parse_and_remap_population_structure('population_structure_matrix.xlsx')

In [145]:
for i, ind in enumerate(example_pop.individuals()):
    ind.primary = np.float(np.argmax(proportions[i]))

In [147]:
example_pop.indInfo('primary')

(1.0,
 5.0,
 3.0,
 2.0,
 5.0,
 5.0,
 3.0,
 0.0,
 3.0,
 3.0,
 5.0,
 3.0,
 0.0,
 2.0,
 1.0,
 5.0,
 4.0,
 1.0,
 4.0,
 1.0,
 3.0,
 1.0,
 5.0,
 3.0,
 1.0,
 5.0,
 4.0,
 3.0,
 5.0,
 1.0,
 2.0,
 1.0,
 1.0,
 0.0,
 3.0,
 3.0,
 3.0,
 1.0,
 0.0,
 0.0,
 5.0,
 0.0,
 2.0,
 3.0,
 3.0,
 1.0,
 1.0,
 4.0,
 1.0,
 0.0,
 0.0,
 3.0,
 2.0,
 3.0,
 2.0,
 2.0,
 0.0,
 3.0,
 3.0,
 2.0,
 3.0,
 2.0,
 1.0,
 3.0,
 1.0,
 5.0,
 1.0,
 3.0,
 2.0,
 5.0,
 0.0,
 5.0,
 0.0,
 3.0,
 3.0,
 1.0,
 3.0,
 3.0,
 5.0,
 1.0,
 5.0,
 2.0,
 3.0,
 1.0,
 1.0,
 0.0,
 3.0,
 3.0,
 3.0,
 0.0,
 4.0,
 3.0,
 0.0,
 4.0,
 2.0,
 2.0,
 2.0,
 3.0,
 3.0,
 0.0,
 0.0,
 3.0,
 3.0,
 4.0,
 3.0)

In [152]:
example_ind = example_pop.individual(0)

In [202]:
mating_pmf = stats.rv_discrete(values=(range(6), proportions[3]), name=str(example_ind.ind_id))

ValueError: The sum of provided pk is not 1.

In [172]:
proportions[3]

array([ 0.    ,  0.4085,  0.5134,  0.0782,  0.    ,  0.    ])

In [168]:
np.round(proportions[3], decimals=4)

array([ 0.    ,  0.4085,  0.5134,  0.0782,  0.    ,  0.    ])

In [201]:
mating_pmf

In [294]:
mating_pmfs = {}
for i, ind in enumerate(example_pop.individuals()):
    print(i)
    mating_pmfs[i+1] = stats.rv_discrete(values=(range(6), proportions[i]), name=str(ind.ind_id))

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104


In [230]:
for i, row in enumerate(proportions):
    if sum(row) > 1:
        least_probability_index = np.argmin(row)
        difference = sum(row) - 1
#        print(i, row, difference)
#        row[least_probability_index] = row[least_probability_index] + difference
        print(i, sum(row), row, difference)
        print(least_probability_index)

3 1.0001 [0.0 0.4085 0.5134 0.0782 0.0 0.0] 9.999999999998899e-05
0
15 1.0001 [0.0908 0.0184 0.0014 0.1178 0.0044 0.7673] 9.999999999998899e-05
2
33 1.0000000000000002 [0.8857 0.0016 0.0009 0.1065 0.0042 0.0011] 2.220446049250313e-16
2
40 1.0001 [0.1428 0.0102 0.0021 0.0813 0.0179 0.7458] 9.999999999998899e-05
2
49 1.0001 [0.7398 0.0062 0.0037 0.1659 0.0581 0.0264] 9.999999999998899e-05
2


In [236]:
np.argmin(proportions[3, np.nonzero(proportions[3]])

SyntaxError: invalid syntax (<ipython-input-236-2a85e5b05eb2>, line 1)

In [240]:
indices = np.nonzero(proportions[3])

TypeError: nonzero() got an unexpected keyword argument 'axis'

In [243]:
indices

(array([1, 2, 3]),)

In [261]:
np.where(proportions[3] > 0)

(array([1, 2, 3]),)

In [266]:
proportions[3, [1,2,3]]

array([0.4085, 0.5134, 0.0782], dtype=object)

In [251]:
values = proportions[3]

In [254]:
np.argmin(values[indices])

2

In [256]:
values[3]

0.0782

In [242]:
np.argmin(proportions[3, indices])

2

In [250]:
proportions[3, 4]

0.0

In [227]:
proportions[3]

array([0.0, 0.4085, 0.5134, 0.0782, 0.0, 0.0], dtype=object)

In [287]:
for i, row in enumerate(proportions):
    if sum(row) > 1:
        greatest_probability_index = np.argmax(proportions[i])
        difference = sum(proportions[i]) - 1
        print(i, sum(proportions[i]), proportions[i], difference)
        proportions[i, greatest_probability_index] = proportions[i, greatest_probability_index] - difference
        print(sum(proportions[i]))

3 1.0001 [0.0 0.4085 0.5134 0.0782 0.0 0.0] 9.999999999998899e-05
1.0
15 1.0001 [0.0908 0.0184 0.0014 0.1178 0.0044 0.7673] 9.999999999998899e-05
1.0
33 1.0000000000000002 [0.8857 0.0016 0.0009 0.1065 0.0042 0.0011] 2.220446049250313e-16
0.9999999999999999
40 1.0001 [0.1428 0.0102 0.0021 0.0813 0.0179 0.7458] 9.999999999998899e-05
1.0
49 1.0001 [0.7398 0.0062 0.0037 0.1659 0.0581 0.0264] 9.999999999998899e-05
1.0


In [290]:
mating_pmf = stats.rv_discrete(values=(range(6), proportions[3]))

In [293]:
for i in range(105):
    if sum(proportions[i]) < 1:
        greatest_probability_index = np.argmax(proportions[i])
        difference = 1 - sum(proportions[i])
        print(i, sum(proportions[i]))
        proportions[i, greatest_probability_index] = proportions[i, greatest_probability_index] + difference
        print(i, sum(proportions[i]))

22 0.9999
22 1.0
29 0.9999999999999999
29 1.0
33 0.9999999999999999
33 1.0
48 0.9999000000000001
48 0.9999999999999999
55 0.9999999999999999
55 1.0000000000000002
65 0.9999
65 1.0
66 0.9999999999999999
66 1.0
72 0.9999999999999999
72 1.0
78 0.9999
78 1.0
80 0.9999999999999999
80 1.0
92 0.9999999999999999
92 1.0
98 0.9999
98 1.0
99 0.9999
99 1.0
102 0.9999999999999999
102 1.0


In [223]:
sum(proportions[3])

1.0004

In [210]:
sum(proportions[3])

-9.999999999998899e-05

In [191]:
sum(proportions[3])

1.0

'2.0'