In [1]:
import numpy as np
import pandas as pd
import h5py
import simuOpt
simuOpt.setOptions(quiet=True, numThreads=4)
import simuPOP as sim
from saegus import analyze, breed, parameters
from bokeh.io import output_notebook, show, export_svgs
from bokeh.layouts import gridplot
from bokeh.plotting import figure, output_file

In [2]:
np.set_printoptions(suppress=True, precision=4)

In [3]:
output_notebook()

Loading BokehJS ...

In [ ]:
p = figure(plot_width=400, plot_height=400, output_backend="svg")
p.quad(top=[2, 3, 4], bottom=[1, 2, 3], left=[1, 2, 3],
      right=[1.2, 2.5, 3.7])

In [ ]:
show(p)

# Visualizing Genetic Map Using Chromosome Ideograms

In [4]:
genetic_map = h5py.File("genetic_map.hdf5")

In [5]:
list(genetic_map)

['chromosome_1',
 'chromosome_10',
 'chromosome_2',
 'chromosome_3',
 'chromosome_4',
 'chromosome_5',
 'chromosome_6',
 'chromosome_7',
 'chromosome_8',
 'chromosome_9',
 'recombination_frequencies']

# Columns in Improved Genetic Map:
    absolute_locus, relative_locus, chromosome, cM

In [13]:
improved_genetic_map = h5py.File("improved_genetic_map.hdf5")

In [104]:
improved_genetic_map.attrs['columns'] = list(map(np.string_, ['absolute_locus, relative_locus,' 
                                                              'chromosome, cM, pairwise_distances']))

In [105]:
improved_genetic_map.attrs['columns']

array([b'absolute_locus, relative_locus,chromosome, cM, pairwise_distances'], 
      dtype='|S68')

In [14]:
chr_1 = np.array(genetic_map['chromosome_1'])

In [22]:
chr_1

array([[    1.    ,     1.    ,    -5.5112],
       [    2.    ,     1.    ,    -5.302 ],
       [    3.    ,     1.    ,    -5.2997],
       ..., 
       [ 6937.    ,     1.    ,   206.2124],
       [ 6938.    ,     1.    ,   206.2276],
       [ 6939.    ,     1.    ,   206.2595]])

In [28]:
chr_1.shape

(6939, 3)

In [85]:
relative_loci = [locus for locus in range(example_pop.numLoci(0))]

In [86]:
improved_chr1 = np.zeros((6939, 5))

In [87]:
improved_chr1[:, 0] = chr_1[:, 0]

In [88]:
relative_loci = np.array(relative_loci)

In [89]:
reindexed_relative_loci = relative_loci + 1

In [90]:
improved_chr1[:, 1] = reindexed_relative_loci

In [126]:
chr_1

array([[    1.    ,     1.    ,    -5.5112],
       [    2.    ,     1.    ,    -5.302 ],
       [    3.    ,     1.    ,    -5.2997],
       ..., 
       [ 6937.    ,     1.    ,   206.2124],
       [ 6938.    ,     1.    ,   206.2276],
       [ 6939.    ,     1.    ,   206.2595]])

In [101]:
improved_chr1[:, 2] = chr_1[:, 1]
improved_chr1[:, 3] = chr_1[:, 2]
cM1 = improved_chr1[:, 3]
pairwise_distances = np.array([np.abs(cM1[i-1] - cM1[i]) for i in range(1, cM1.shape[0])] + [0])/100
improved_chr1[:, 4] = pairwise_distances

In [127]:
chr_1

array([[    1.    ,     1.    ,    -5.5112],
       [    2.    ,     1.    ,    -5.302 ],
       [    3.    ,     1.    ,    -5.2997],
       ..., 
       [ 6937.    ,     1.    ,   206.2124],
       [ 6938.    ,     1.    ,   206.2276],
       [ 6939.    ,     1.    ,   206.2595]])

In [102]:
improved_chr1

array([[    1.    ,     1.    ,     1.    ,    -5.5112,     0.0021],
       [    2.    ,     2.    ,     1.    ,    -5.302 ,     0.    ],
       [    3.    ,     3.    ,     1.    ,    -5.2997,     0.0004],
       ..., 
       [ 6937.    ,  6937.    ,     1.    ,   206.2124,     0.0002],
       [ 6938.    ,  6938.    ,     1.    ,   206.2276,     0.0003],
       [ 6939.    ,  6939.    ,     1.    ,   206.2595,     0.    ]])

In [130]:
improved_chromosome

array([[  6940.    ,      0.    ,      2.    ,      2.3445,      0.    ],
       [  6941.    ,      1.    ,      2.    ,      2.3447,      0.    ],
       [  6942.    ,      2.    ,      2.    ,      2.5631,      0.    ],
       ..., 
       [ 12108.    ,   5168.    ,      2.    ,    158.4893,      0.    ],
       [ 12109.    ,   5169.    ,      2.    ,    158.4969,      0.    ],
       [ 12110.    ,   5170.    ,      2.    ,    158.4973,      0.    ]])

In [145]:
improved_genetic_map['chromosome_2'][:, 1] = improved_genetic_map['chromosome_2'][:, 1] + 1

In [ ]:
improved_genetic_map['chromosome_']

In [138]:
for i in range(2, 11):
    current_chromosome = genetic_map['chromosome_' + str(i)]
    improved_chromosome = np.zeros((current_chromosome.shape[0], 5))
    improved_chromosome[:, 0] = current_chromosome[:, 0]
    improved_chromosome[:, 1] = np.array([locus for locus in range(example_pop.numLoci(i-1))]) + 1
    improved_chromosome[:, 2] = current_chromosome[:, 1]
    improved_chromosome[:, 3] = current_chromosome[:, 2]
    cM = current_chromosome[:, 2]
    improved_chromosome[:, 4] = np.array([np.abs(cM[i-1] - cM[i]) for i in range(1, cM.shape[0])] 
                                         + [0])/100
    improved_genetic_map['chromosome_' + str(i)] = improved_chromosome

RuntimeError: Unable to create link (Name already exists)

In [151]:
for i in range(3, 11):
    improved_genetic_map['chromosome_' + str(i)][:, 1] = improved_genetic_map['chromosome_' + str(i)][:, 1] + 1 

In [157]:
improved_genetic_map['chromosome_7'][:, 1]

array([    1.,     2.,     3., ...,  3773.,  3774.,  3775.])

In [158]:
improved_genetic_map.close()

In [60]:
np.abs(cM1[0] - cM1[1])

0.20926625899999962

# Plot of $$|L_{i-1} - L_i|$$

In [118]:
cM1 = improved_chr1[:, 3]
pairwise_distances = np.array([np.abs(cM1[i-1] - cM1[i]) for i in range(1, cM1.shape[0])])/100
#negative_ln_recombs = -1*np.log(pairwise_distances)
hist, edges = np.histogram(pairwise_distances, density=True, bins=50)

In [119]:
hist

array([ 3343.8478,   407.5038,   269.1705,   199.6632,   117.8899,
          88.5878,    60.6486,    46.3382,    46.3382,    32.0279,
          21.8062,    15.6732,    17.7176,     7.4959,     6.8144,
           8.8588,     4.0887,     2.0443,     6.133 ,     1.3629,
           1.3629,     2.0443,     2.0443,     1.3629,     2.0443,
           0.6814,     2.0443,     2.7258,     0.6814,     0.    ,
           1.3629,     2.0443,     0.    ,     0.    ,     0.6814,
           2.0443,     0.    ,     0.    ,     0.6814,     0.    ,
           0.6814,     0.    ,     0.    ,     0.    ,     0.    ,
           0.    ,     0.6814,     0.    ,     0.    ,     0.6814])

In [120]:
genmap_distances = figure(title="Distribution of Pairwise cM Distances: Chromosome 1",
                          tools="save", 
                          background_fill_color="#E8DDCB", 
                          output_backend="svg")

genmap_distances.quad(top=hist, bottom=0, left=edges[:-1], right=edges[1:],
        fill_color="#036564", line_color="#033649")

genmap_distances.legend.location = "center_right"
genmap_distances.legend.background_fill_color = "darkgrey"
genmap_distances.xaxis.axis_label = '-ln(|cM_i-1, cM_i|)'
genmap_distances.yaxis.axis_label = 'frequency'

In [121]:
show(genmap_distances)

# Plot of $$-ln(|L_{i-1} - L_i|)$$

In [122]:
cM1 = improved_chr1[:, 3]
pairwise_distances = np.array([np.abs(cM1[i-1] - cM1[i]) for i in range(1, cM1.shape[0])])/100
negative_ln_recombs = -1*np.log(pairwise_distances)
hist, edges = np.histogram(negative_ln_recombs, density=True, bins=50)

In [123]:
genmap_distances = figure(title="Distribution of Pairwise cM Distances: Chromosome 1",
                          tools="save", 
                          background_fill_color="#E8DDCB", 
                          output_backend="svg")

genmap_distances.quad(top=hist, bottom=0, left=edges[:-1], right=edges[1:],
        fill_color="#036564", line_color="#033649")

genmap_distances.legend.location = "center_right"
genmap_distances.legend.background_fill_color = "darkgrey"
genmap_distances.xaxis.axis_label = '-ln(|cM_i-1, cM_i|)'
genmap_distances.yaxis.axis_label = 'frequency'

In [124]:
show(genmap_distances)

In [15]:
chr_2 = np.array(genetic_map['chromosome_2'])

In [18]:
chr_2

array([[  6940.    ,      2.    ,      2.3445],
       [  6941.    ,      2.    ,      2.3447],
       [  6942.    ,      2.    ,      2.5631],
       ..., 
       [ 12108.    ,      2.    ,    158.4893],
       [ 12109.    ,      2.    ,    158.4969],
       [ 12110.    ,      2.    ,    158.4973]])

In [7]:
example_pop = sim.loadPopulation('example_pop.pop')

In [ ]:
np.zeros((4))

In [12]:
example_pop.numLoci()

(6939, 5171, 4974, 4819, 4838, 3570, 3775, 3849, 3337, 3173)

In [ ]:
for number_loci in example_pop.numLoci():
    

In [11]:
example_pop.chromLocusPair(1)

(0, 1)

In [ ]:
gene

In [159]:
gen_map = pd.read_csv('example_genetic_map.txt', index_col=0, sep='\t')

In [ ]:
gen_map

In [160]:
gen_map.loc[gen_map['chr'] == 1]

chr          cM
locus                 
1        1   -5.511247
2        1   -5.301981
3        1   -5.299719
4        1   -5.256896
5        1   -5.225641
6        1   -5.078748
7        1   -5.057972
8        1   -4.937512
9        1   -4.897494
10       1   -4.664195
11       1   -4.579351
12       1   -4.558724
13       1   -4.217548
14       1   -4.161764
15       1   -4.159979
16       1   -3.949824
17       1   -3.792475
18       1   -3.385915
19       1   -3.359243
20       1   -3.356172
21       1   -3.341472
22       1   -3.341145
23       1   -3.340715
24       1   -3.335458
25       1   -3.331318
26       1   -2.810058
27       1   -2.786785
28       1   -2.309115
29       1   -1.879238
30       1   -1.876714
...    ...         ...
6910     1  204.921183
6911     1  204.921317
6912     1  204.921939
6913     1  204.922155
6914     1  204.927964
6915     1  204.927972
6916     1  204.949257
6917     1  205.203694
6918     1  205.244025
6919     1  205.267187
6920     1  205.365932
6921     1  205.394367
6922     1  205.395042
6923     1  205.396565
6924     1  205.399220
6925     1  205.486207
6926     1  205.486316
6927     1  205.488856
6928     1  205.594456
6929     1  205.682266
6930     1  205.684207
6931     1  205.700326
6932     1  205.700359
6933     1  205.786769
6934     1  206.039971
6935     1  206.059044
6936     1  206.170457
6937     1  206.212414
6938     1  206.227631
6939     1  206.259453

[6939 rows x 2 columns]

In [ ]:
gen_map.loc[gen_map['chr'] == 2]

In [ ]:
gen_map.loc[gen_map['chr'] == 3]

In [ ]:
gen_map.loc[gen_map['chr'] == 4]

In [ ]:
gen_map.loc[gen_map['chr'] == 5]

In [ ]:
gen_map.loc[gen_map['chr'] == 6]

In [ ]:
gen_map.loc[gen_map['chr'] == 7]

In [ ]:
gen_map.loc[gen_map['chr'] == 8]

In [ ]:
gen_map.loc[gen_map['chr'] == 9].cM

In [ ]:
max(gen_map.loc[gen_map['chr'] == 10].cM)

In [ ]:
chromosome_bottoms = [min(gen_map.loc[gen_map['chr'] == i].cM) for i in range(1, 11)]
chromosome_tops = [max(gen_map.loc[gen_map['chr'] == i].cM) for i in range(1, 11)]
chromosome_factors = [str(i) for i in range(1, 11)]

In [ ]:
chromosome_bottoms

In [ ]:
chromosome_tops

In [ ]:
chrom_ideograms = figure(plot_width=960, plot_height=960, x_range=chromosome_factors,
                         title="Chromosome Ideogram Figure",
                        output_backend="svg")

In [ ]:
chrom_ideograms.xgrid.grid_line_color = None
chrom_ideograms.ygrid.grid_line_color = None

In [ ]:
chrom_ideograms.vbar(x=chromosome_factors, top=chromosome_tops, bottom=chromosome_bottoms, width=0.25,
                    line_width=1.0, line_color='black', fill_color='green',
                    alpha=0.5)

In [ ]:
chrom_ideograms.xaxis.axis_label="Chromosome"
chrom_ideograms.xaxis.axis_label_text_font_size="24pt"
chrom_ideograms.xaxis.axis_label_text_font_style="bold"

In [ ]:
chrom_ideograms.yaxis.axis_label="cM"
chrom_ideograms.yaxis.axis_label_text_font_size="24pt"
chrom_ideograms.yaxis.axis_label_text_font_style="bold"

In [ ]:
show(chrom_ideograms)

# Example Distribution Plot

In [73]:
import scipy.special

p1 = figure(title="Normal Distribution (μ=0, σ=0.5)",tools="save",
            background_fill_color="#E8DDCB", output_backend="svg")

mu, sigma = 0, 0.5

measured = np.random.normal(mu, sigma, 1000)
hist, edges = np.histogram(measured, density=True, bins=50)

x = np.linspace(-2, 2, 1000)
pdf = 1/(sigma * np.sqrt(2*np.pi)) * np.exp(-(x-mu)**2 / (2*sigma**2))
cdf = (1+scipy.special.erf((x-mu)/np.sqrt(2*sigma**2)))/2

p1.quad(top=hist, bottom=0, left=edges[:-1], right=edges[1:],
        fill_color="#036564", line_color="#033649")
p1.line(x, pdf, line_color="#D95B43", line_width=8, alpha=0.7, legend="PDF")
p1.line(x, cdf, line_color="white", line_width=2, alpha=0.7, legend="CDF")

p1.legend.location = "center_right"
p1.legend.background_fill_color = "darkgrey"
p1.xaxis.axis_label = 'x'
p1.yaxis.axis_label = 'Pr(x)'

In [74]:
show(p1)

In [ ]:
trait_data = h5py.File("example_trait_data.hdf5")

In [ ]:
qtl = list(trait_data['qtl'])

In [ ]:
allele_effects = np.array(trait_data['allele/effects'])

In [ ]:
allele_fx = np.array(allele_effects[qtl])

In [ ]:
import numpy as np
import scipy.special

from bokeh.layouts import gridplot
from bokeh.plotting import figure, show, output_file

example_exponential = figure(title="Exponential Distribution theta=0",tools="save",
            background_fill_color="#E8DDCB", output_backend="svg")

theta = 1

expo_measured = np.random.exponential(theta, 1000)
expo_hist, expo_edges = np.histogram(expo_measured, density=True, bins=70)

x = np.linspace(0.01, 6, 2000)
expo_pdf = np.exp(-(x))
#pdf = 1/(sigma * np.sqrt(2*np.pi)) * np.exp(-(x-mu)**2 / (2*sigma**2))
#cdf = (1+scipy.special.erf((x-mu)/np.sqrt(2*sigma**2)))/2

example_exponential.quad(top=expo_hist, bottom=0, left=expo_edges[:-1], right=expo_edges[1:],
        fill_color="#036564", line_color="#033649")
example_exponential.line(x, expo_pdf, line_color="#D95B43", line_width=8, alpha=0.7, legend="PDF")
#example_exponential.line(x, cdf, line_color="white", line_width=2, alpha=0.7, legend="CDF")

example_exponential.legend.location = "center_right"
example_exponential.legend.background_fill_color = "darkgrey"
example_exponential.xaxis.axis_label = 'x'
example_exponential.yaxis.axis_label = 'Pr(x)'

In [ ]:
show(example_exponential)

In [ ]:
expo_hist

In [ ]:
allele_fx[:, 2]

In [ ]:
min(abs(x - allele_fx[0, 2]))

In [ ]:
np.where(min(abs(x - allele_fx[0, 2])))

In [ ]:
allele_fx[0, 2]

In [ ]:
np.min(np.absolute(x - allele_fx[0, 2]))

In [ ]:
for i in range(100, 170):
    print(i, x[i] - allele_fx[0, 2])

In [ ]:
np.array([x[i] - allele_fx[0, 2] for i in range(100, 200) if x[i] - allele_fx[0, 2] > 0])

In [ ]:
x[164]

In [ ]:
np.absolute()

In [ ]:
allele_fx

In [ ]:
x

In [ ]:
expo_edges

In [ ]:
allele_fx[:, 2]

In [ ]:
allele_fx[:, 4]

In [ ]:
x[::50]

In [ ]:
combined = list(allele_fx[:, 2]) + list(x)

## Output in PNG

In [ ]:
import scipy.special
from bokeh.layouts import gridplot
from bokeh.plotting import figure, show, output_file

example_normal = figure(title="Normal Distribution (mu=0, sigma^2=1)",tools="save",
            background_fill_color="#E8DDCB")

mu = 0
sigma = 1

measured = np.random.normal(mu, sigma, 1000)
hist, edges = np.histogram(measured, density=True, bins=70)

x = np.linspace(-3, 3, 1000)
#expo_pdf = np.exp(-(x))
pdf = 1/(sigma * np.sqrt(2*np.pi)) * np.exp(-(x-mu)**2 / (2*sigma**2))
#cdf = (1+scipy.special.erf((x-mu)/np.sqrt(2*sigma**2)))/2

example_normal.quad(top=hist, bottom=0, left=edges[:-1], right=edges[1:],
        fill_color="#036564", line_color="#033649")
example_normal.line(x, pdf, line_color="#D95B43", line_width=8, alpha=0.7, legend="PDF")
#example_exponential.line(x, cdf, line_color="white", line_width=2, alpha=0.7, legend="CDF")

example_normal.legend.location = "center_right"
example_normal.legend.background_fill_color = "darkgrey"
example_normal.xaxis.axis_label = 'x'
example_normal.yaxis.axis_label = 'Pr(x)'

In [ ]:
show(example_normal)

## Output in SVG

In [ ]:
import scipy.special
from bokeh.layouts import gridplot
from bokeh.plotting import figure, show, output_file

example_normal = figure(title="Normal Distribution (mu=0, sigma^2=1)",tools="save",
            background_fill_color="#E8DDCB", output_backend="svg")

mu = 0
sigma = 1

measured = np.random.normal(mu, sigma, 1000)
hist, edges = np.histogram(measured, density=True, bins=70)

x = np.linspace(-3, 3, 1000)
#expo_pdf = np.exp(-(x))
pdf = 1/(sigma * np.sqrt(2*np.pi)) * np.exp(-(x-mu)**2 / (2*sigma**2))
#cdf = (1+scipy.special.erf((x-mu)/np.sqrt(2*sigma**2)))/2

example_normal.quad(top=hist, bottom=0, left=edges[:-1], right=edges[1:],
        fill_color="#036564", line_color="#033649")
example_normal.line(x, pdf, line_color="#D95B43", line_width=8, alpha=0.7, legend="PDF")
#example_exponential.line(x, cdf, line_color="white", line_width=2, alpha=0.7, legend="CDF")

example_normal.legend.location = "center_right"
example_normal.legend.background_fill_color = "darkgrey"
example_normal.xaxis.axis_label = 'x'
example_normal.yaxis.axis_label = 'Pr(x)'

In [ ]:
show(example_normal)

In [ ]:
import numpy as np
import scipy.special

from bokeh.layouts import gridplot
from bokeh.plotting import figure, show, output_file

example_exponential = figure(title="Exponential Distribution theta=0",tools="save",
            background_fill_color="#E8DDCB")

theta = 1

measured = np.random.exponential(theta, 1000)
hist, edges = np.histogram(measured, density=True, bins=50)

x = np.linspace(-2, 2, 1000)
expo_pdf = np.exp(-(x))
#pdf = 1/(sigma * np.sqrt(2*np.pi)) * np.exp(-(x-mu)**2 / (2*sigma**2))
#cdf = (1+scipy.special.erf((x-mu)/np.sqrt(2*sigma**2)))/2

p1.quad(top=hist, bottom=0, left=edges[:-1], right=edges[1:],
        fill_color="#036564", line_color="#033649")
p1.line(x, pdf, line_color="#D95B43", line_width=8, alpha=0.7, legend="PDF")
p1.line(x, cdf, line_color="white", line_width=2, alpha=0.7, legend="CDF")

p1.legend.location = "center_right"
p1.legend.background_fill_color = "darkgrey"
p1.xaxis.axis_label = 'x'
p1.yaxis.axis_label = 'Pr(x)'



p2 = figure(title="Log Normal Distribution (μ=0, σ=0.5)", tools="save",
            background_fill_color="#E8DDCB")

mu, sigma = 0, 0.5

measured = np.random.lognormal(mu, sigma, 1000)
hist, edges = np.histogram(measured, density=True, bins=50)

x = np.linspace(0.0001, 8.0, 1000)
pdf = 1/(x* sigma * np.sqrt(2*np.pi)) * np.exp(-(np.log(x)-mu)**2 / (2*sigma**2))
cdf = (1+scipy.special.erf((np.log(x)-mu)/(np.sqrt(2)*sigma)))/2

p2.quad(top=hist, bottom=0, left=edges[:-1], right=edges[1:],
        fill_color="#036564", line_color="#033649")
p2.line(x, pdf, line_color="#D95B43", line_width=8, alpha=0.7, legend="PDF")
p2.line(x, cdf, line_color="white", line_width=2, alpha=0.7, legend="CDF")

p2.legend.location = "center_right"
p2.legend.background_fill_color = "darkgrey"
p2.xaxis.axis_label = 'x'
p2.yaxis.axis_label = 'Pr(x)'



p3 = figure(title="Gamma Distribution (k=1, θ=2)", tools="save",
            background_fill_color="#E8DDCB")

k, theta = 1.0, 2.0

measured = np.random.gamma(k, theta, 1000)
hist, edges = np.histogram(measured, density=True, bins=50)

x = np.linspace(0.0001, 20.0, 1000)
pdf = x**(k-1) * np.exp(-x/theta) / (theta**k * scipy.special.gamma(k))
cdf = scipy.special.gammainc(k, x/theta) / scipy.special.gamma(k)

p3.quad(top=hist, bottom=0, left=edges[:-1], right=edges[1:],
        fill_color="#036564", line_color="#033649")
p3.line(x, pdf, line_color="#D95B43", line_width=8, alpha=0.7, legend="PDF")
p3.line(x, cdf, line_color="white", line_width=2, alpha=0.7, legend="CDF")

p3.legend.location = "center_right"
p3.legend.background_fill_color = "darkgrey"
p3.xaxis.axis_label = 'x'
p3.yaxis.axis_label = 'Pr(x)'



p4 = figure(title="Weibull Distribution (λ=1, k=1.25)", tools="save",
            background_fill_color="#E8DDCB")

lam, k = 1, 1.25

measured = lam*(-np.log(np.random.uniform(0, 1, 1000)))**(1/k)
hist, edges = np.histogram(measured, density=True, bins=50)

x = np.linspace(0.0001, 8, 1000)
pdf = (k/lam)*(x/lam)**(k-1) * np.exp(-(x/lam)**k)
cdf = 1 - np.exp(-(x/lam)**k)

p4.quad(top=hist, bottom=0, left=edges[:-1], right=edges[1:],
       fill_color="#036564", line_color="#033649")
p4.line(x, pdf, line_color="#D95B43", line_width=8, alpha=0.7, legend="PDF")
p4.line(x, cdf, line_color="white", line_width=2, alpha=0.7, legend="CDF")

p4.legend.location = "center_right"
p4.legend.background_fill_color = "darkgrey"
p4.xaxis.axis_label = 'x'
p4.yaxis.axis_label = 'Pr(x)'

show(gridplot(p1,p2,p3,p4, ncols=2, plot_width=400, plot_height=400))

In [ ]:
import networkx as nx

from bokeh.io import show, output_file
from bokeh.models import Plot, Range1d, MultiLine, Circle, HoverTool, TapTool, BoxSelectTool
from bokeh.models.graphs import from_networkx, NodesAndLinkedEdges, EdgesAndLinkedNodes
from bokeh.palettes import Spectral4

G=nx.karate_club_graph()

plot = Plot(plot_width=400, plot_height=400,
            x_range=Range1d(-1.1,1.1), y_range=Range1d(-1.1,1.1))
plot.title.text = "Graph Interaction Demonstration"

plot.add_tools(HoverTool(tooltips=None), TapTool(), BoxSelectTool())

graph_renderer = from_networkx(G, nx.circular_layout, scale=1, center=(0,0))

graph_renderer.node_renderer.glyph = Circle(size=15, fill_color=Spectral4[0])
graph_renderer.node_renderer.selection_glyph = Circle(size=15, fill_color=Spectral4[2])
graph_renderer.node_renderer.hover_glyph = Circle(size=15, fill_color=Spectral4[1])

graph_renderer.edge_renderer.glyph = MultiLine(line_color="#CCCCCC", line_alpha=0.8, line_width=5)
graph_renderer.edge_renderer.selection_glyph = MultiLine(line_color=Spectral4[2], line_width=5)
graph_renderer.edge_renderer.hover_glyph = MultiLine(line_color=Spectral4[1], line_width=5)

graph_renderer.selection_policy = NodesAndLinkedEdges()
graph_renderer.inspection_policy = EdgesAndLinkedNodes()

plot.renderers.append(graph_renderer)

output_file("interactive_graphs.html")
show(plot)